// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: careerpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CareerInfoGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CareerInfoGetRequest) Reset() {
	*x = CareerInfoGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareerInfoGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerInfoGetRequest) ProtoMessage() {}

func (x *CareerInfoGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerInfoGetRequest.ProtoReflect.Descriptor instead.
func (*CareerInfoGetRequest) Descriptor() ([]byte, []int) {
	return file_careerpb_proto_rawDescGZIP(), []int{0}
}

// 作物/花卉收获排行条目（仅含 fruit_id + count，名字/头像由后端按 ItemInfo 装饰）
type CareerStatItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FruitId int64 `protobuf:"varint,1,opt,name=fruit_id,json=fruitId,proto3" json:"fruit_id,omitempty"`
	Count   int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CareerStatItem) Reset() {
	*x = CareerStatItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareerStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerStatItem) ProtoMessage() {}

func (x *CareerStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_careerpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerStatItem.ProtoReflect.Descriptor instead.
func (*CareerStatItem) Descriptor() ([]byte, []int) {
	return file_careerpb_proto_rawDescGZIP(), []int{1}
}

func (x *CareerStatItem) GetFruitId() int64 {
	if x != nil {
		return x.FruitId
	}
	return 0
}

func (x *CareerStatItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 玩家达到某等级解锁的统计
type CareerLevelStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FruitId int64 `protobuf:"varint,1,opt,name=fruit_id,json=fruitId,proto3" json:"fruit_id,omitempty"`
	Count   int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Level   int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *CareerLevelStat) Reset() {
	*x = CareerLevelStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareerLevelStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerLevelStat) ProtoMessage() {}

func (x *CareerLevelStat) ProtoReflect() protoreflect.Message {
	mi := &file_careerpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerLevelStat.ProtoReflect.Descriptor instead.
func (*CareerLevelStat) Descriptor() ([]byte, []int) {
	return file_careerpb_proto_rawDescGZIP(), []int{2}
}

func (x *CareerLevelStat) GetFruitId() int64 {
	if x != nil {
		return x.FruitId
	}
	return 0
}

func (x *CareerLevelStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CareerLevelStat) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 完整响应
type CareerInfoGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items          []*CareerStatItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                                           // 收获排行（按 count 倒序）
	StatsTotal     int64              `protobuf:"varint,2,opt,name=stats_total,json=statsTotal,proto3" json:"stats_total,omitempty"`              // 总收获数（备用统计）
	StatsCount     int64              `protobuf:"varint,3,opt,name=stats_count,json=statsCount,proto3" json:"stats_count,omitempty"`              // 排行榜类型数（备用统计）
	Name           string             `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                             // 玩家昵称
	Avatar         string             `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`                                         // 玩家头像 URL
	Level          int32              `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`                                          // 玩家等级 Lv
	Exp            int64              `protobuf:"varint,10,opt,name=exp,proto3" json:"exp,omitempty"`                                             // 经验值
	Gid            int64              `protobuf:"varint,11,opt,name=gid,proto3" json:"gid,omitempty"`                                             // 角色编号（游戏内唯一 id）
	LevelStats     []*CareerLevelStat `protobuf:"bytes,12,rep,name=level_stats,json=levelStats,proto3" json:"level_stats,omitempty"`              // 玩家等级达成统计
	AchievedLevels int32              `protobuf:"varint,13,opt,name=achieved_levels,json=achievedLevels,proto3" json:"achieved_levels,omitempty"` // 玩家达成等级数
	Openid         string             `protobuf:"bytes,15,opt,name=openid,proto3" json:"openid,omitempty"`                                        // 玩家 openid
}

func (x *CareerInfoGetReply) Reset() {
	*x = CareerInfoGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareerInfoGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareerInfoGetReply) ProtoMessage() {}

func (x *CareerInfoGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_careerpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareerInfoGetReply.ProtoReflect.Descriptor instead.
func (*CareerInfoGetReply) Descriptor() ([]byte, []int) {
	return file_careerpb_proto_rawDescGZIP(), []int{3}
}

func (x *CareerInfoGetReply) GetItems() []*CareerStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CareerInfoGetReply) GetStatsTotal() int64 {
	if x != nil {
		return x.StatsTotal
	}
	return 0
}

func (x *CareerInfoGetReply) GetStatsCount() int64 {
	if x != nil {
		return x.StatsCount
	}
	return 0
}

func (x *CareerInfoGetReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CareerInfoGetReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CareerInfoGetReply) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CareerInfoGetReply) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *CareerInfoGetReply) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *CareerInfoGetReply) GetLevelStats() []*CareerLevelStat {
	if x != nil {
		return x.LevelStats
	}
	return nil
}

func (x *CareerInfoGetReply) GetAchievedLevels() int32 {
	if x != nil {
		return x.AchievedLevels
	}
	return 0
}

func (x *CareerInfoGetReply) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

var File_careerpb_proto protoreflect.FileDescriptor

var file_careerpb_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x70,
	0x62, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x0e, 0x43, 0x61, 0x72,
	0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x72, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66,
	0x72, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x58, 0x0a, 0x0f,
	0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x72, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x66, 0x72, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xf7, 0x02, 0x0a, 0x12, 0x43, 0x61, 0x72, 0x65, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x43,
	0x61, 0x72, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x0b,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76,
	0x65, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64,
	0x32, 0x6c, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5b, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x12, 0x25, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x63, 0x61, 0x72, 0x65,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x70, 0x62, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x65,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73,
	0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_careerpb_proto_rawDescOnce sync.Once
	file_careerpb_proto_rawDescData = file_careerpb_proto_rawDesc
)

func file_careerpb_proto_rawDescGZIP() []byte {
	file_careerpb_proto_rawDescOnce.Do(func() {
		file_careerpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_careerpb_proto_rawDescData)
	})
	return file_careerpb_proto_rawDescData
}

var file_careerpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_careerpb_proto_goTypes = []interface{}{
	(*CareerInfoGetRequest)(nil), // 0: gamepb.careerpb.CareerInfoGetRequest
	(*CareerStatItem)(nil),       // 1: gamepb.careerpb.CareerStatItem
	(*CareerLevelStat)(nil),      // 2: gamepb.careerpb.CareerLevelStat
	(*CareerInfoGetReply)(nil),   // 3: gamepb.careerpb.CareerInfoGetReply
}
var file_careerpb_proto_depIdxs = []int32{
	1, // 0: gamepb.careerpb.CareerInfoGetReply.items:type_name -> gamepb.careerpb.CareerStatItem
	2, // 1: gamepb.careerpb.CareerInfoGetReply.level_stats:type_name -> gamepb.careerpb.CareerLevelStat
	0, // 2: gamepb.careerpb.CareerService.CareerInfoGet:input_type -> gamepb.careerpb.CareerInfoGetRequest
	3, // 3: gamepb.careerpb.CareerService.CareerInfoGet:output_type -> gamepb.careerpb.CareerInfoGetReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_careerpb_proto_init() }
func file_careerpb_proto_init() {
	if File_careerpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_careerpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareerInfoGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareerStatItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareerLevelStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareerInfoGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_careerpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_careerpb_proto_goTypes,
		DependencyIndexes: file_careerpb_proto_depIdxs,
		MessageInfos:      file_careerpb_proto_msgTypes,
	}.Build()
	File_careerpb_proto = out.File
	file_careerpb_proto_rawDesc = nil
	file_careerpb_proto_goTypes = nil
	file_careerpb_proto_depIdxs = nil
}
