// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: corepb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 通用物品 ============
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 物品ID
	Count      int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // 数量
	ExpireTime int64 `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间
	// field 4 reserved
	// google.protobuf.Any detail = 5;  // 详情 (略)
	Uid         int64   `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`                                           // UID
	IsNew       bool    `protobuf:"varint,7,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`                          // 是否新获得
	MutantTypes []int64 `protobuf:"varint,8,rep,packed,name=mutant_types,json=mutantTypes,proto3" json:"mutant_types,omitempty"` // 变异类型
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_corepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *Item) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Item) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Item) GetMutantTypes() []int64 {
	if x != nil {
		return x.MutantTypes
	}
	return nil
}

// 背包（物品列表）
type ItemBag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ItemBag) Reset() {
	*x = ItemBag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_corepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBag) ProtoMessage() {}

func (x *ItemBag) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBag.ProtoReflect.Descriptor instead.
func (*ItemBag) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{1}
}

func (x *ItemBag) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// ============ 物品变化 ============
type ItemChg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item  *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`    // 物品信息
	Delta int64 `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // 变化量 (正数增加, 负数减少)
}

func (x *ItemChg) Reset() {
	*x = ItemChg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_corepb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemChg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemChg) ProtoMessage() {}

func (x *ItemChg) ProtoReflect() protoreflect.Message {
	mi := &file_corepb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemChg.ProtoReflect.Descriptor instead.
func (*ItemChg) Descriptor() ([]byte, []int) {
	return file_corepb_proto_rawDescGZIP(), []int{2}
}

func (x *ItemChg) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemChg) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_corepb_proto protoreflect.FileDescriptor

var file_corepb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x22, 0x99, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6e,
	0x65, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x12,
	0x21, 0x0a, 0x0c, 0x6d, 0x75, 0x74, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x75, 0x74, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x22, 0x2d, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x67, 0x12, 0x22, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x41, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x68, 0x67, 0x12, 0x20, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61,
	0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_corepb_proto_rawDescOnce sync.Once
	file_corepb_proto_rawDescData = file_corepb_proto_rawDesc
)

func file_corepb_proto_rawDescGZIP() []byte {
	file_corepb_proto_rawDescOnce.Do(func() {
		file_corepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_corepb_proto_rawDescData)
	})
	return file_corepb_proto_rawDescData
}

var file_corepb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_corepb_proto_goTypes = []interface{}{
	(*Item)(nil),    // 0: corepb.Item
	(*ItemBag)(nil), // 1: corepb.ItemBag
	(*ItemChg)(nil), // 2: corepb.ItemChg
}
var file_corepb_proto_depIdxs = []int32{
	0, // 0: corepb.ItemBag.items:type_name -> corepb.Item
	0, // 1: corepb.ItemChg.item:type_name -> corepb.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_corepb_proto_init() }
func file_corepb_proto_init() {
	if File_corepb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_corepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_corepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemBag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_corepb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemChg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_corepb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_corepb_proto_goTypes,
		DependencyIndexes: file_corepb_proto_depIdxs,
		MessageInfos:      file_corepb_proto_msgTypes,
	}.Build()
	File_corepb_proto = out.File
	file_corepb_proto_rawDesc = nil
	file_corepb_proto_goTypes = nil
	file_corepb_proto_depIdxs = nil
}
