// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: dogpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DogInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpireTime int64 `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Status     int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Level      int32 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Active     int32 `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *DogInfo) Reset() {
	*x = DogInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogInfo) ProtoMessage() {}

func (x *DogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogInfo.ProtoReflect.Descriptor instead.
func (*DogInfo) Descriptor() ([]byte, []int) {
	return file_dogpb_proto_rawDescGZIP(), []int{0}
}

func (x *DogInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DogInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *DogInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DogInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DogInfo) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

type GetDogInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostGid int64 `protobuf:"varint,1,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"`
}

func (x *GetDogInfoRequest) Reset() {
	*x = GetDogInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDogInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogInfoRequest) ProtoMessage() {}

func (x *GetDogInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDogInfoRequest) Descriptor() ([]byte, []int) {
	return file_dogpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetDogInfoRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type GetDogInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dogs        []*DogInfo `protobuf:"bytes,1,rep,name=dogs,proto3" json:"dogs,omitempty"`
	Coin        int64      `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
	ProtectTime int64      `protobuf:"varint,4,opt,name=protect_time,json=protectTime,proto3" json:"protect_time,omitempty"`
	Foods       []*DogFood `protobuf:"bytes,5,rep,name=foods,proto3" json:"foods,omitempty"`
}

func (x *GetDogInfoReply) Reset() {
	*x = GetDogInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDogInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogInfoReply) ProtoMessage() {}

func (x *GetDogInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogInfoReply.ProtoReflect.Descriptor instead.
func (*GetDogInfoReply) Descriptor() ([]byte, []int) {
	return file_dogpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetDogInfoReply) GetDogs() []*DogInfo {
	if x != nil {
		return x.Dogs
	}
	return nil
}

func (x *GetDogInfoReply) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *GetDogInfoReply) GetProtectTime() int64 {
	if x != nil {
		return x.ProtectTime
	}
	return 0
}

func (x *GetDogInfoReply) GetFoods() []*DogFood {
	if x != nil {
		return x.Foods
	}
	return nil
}

type DogFood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Duration int64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Count    int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DogFood) Reset() {
	*x = DogFood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dogpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DogFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogFood) ProtoMessage() {}

func (x *DogFood) ProtoReflect() protoreflect.Message {
	mi := &file_dogpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogFood.ProtoReflect.Descriptor instead.
func (*DogFood) Descriptor() ([]byte, []int) {
	return file_dogpb_proto_rawDescGZIP(), []int{3}
}

func (x *DogFood) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DogFood) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *DogFood) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_dogpb_proto protoreflect.FileDescriptor

var file_dogpb_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x6f, 0x67, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x64, 0x6f, 0x67, 0x70, 0x62, 0x22, 0x80, 0x01, 0x0a, 0x07,
	0x44, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x2e,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x67, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x47, 0x69, 0x64, 0x22, 0xa0,
	0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x64, 0x6f, 0x67, 0x70, 0x62, 0x2e,
	0x44, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x6f, 0x67, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x69,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x64, 0x6f, 0x67,
	0x70, 0x62, 0x2e, 0x44, 0x6f, 0x67, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x05, 0x66, 0x6f, 0x6f, 0x64,
	0x73, 0x22, 0x4b, 0x0a, 0x07, 0x44, 0x6f, 0x67, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73,
	0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dogpb_proto_rawDescOnce sync.Once
	file_dogpb_proto_rawDescData = file_dogpb_proto_rawDesc
)

func file_dogpb_proto_rawDescGZIP() []byte {
	file_dogpb_proto_rawDescOnce.Do(func() {
		file_dogpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_dogpb_proto_rawDescData)
	})
	return file_dogpb_proto_rawDescData
}

var file_dogpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dogpb_proto_goTypes = []interface{}{
	(*DogInfo)(nil),           // 0: gamepb.dogpb.DogInfo
	(*GetDogInfoRequest)(nil), // 1: gamepb.dogpb.GetDogInfoRequest
	(*GetDogInfoReply)(nil),   // 2: gamepb.dogpb.GetDogInfoReply
	(*DogFood)(nil),           // 3: gamepb.dogpb.DogFood
}
var file_dogpb_proto_depIdxs = []int32{
	0, // 0: gamepb.dogpb.GetDogInfoReply.dogs:type_name -> gamepb.dogpb.DogInfo
	3, // 1: gamepb.dogpb.GetDogInfoReply.foods:type_name -> gamepb.dogpb.DogFood
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dogpb_proto_init() }
func file_dogpb_proto_init() {
	if File_dogpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dogpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DogInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDogInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDogInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dogpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DogFood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dogpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dogpb_proto_goTypes,
		DependencyIndexes: file_dogpb_proto_depIdxs,
		MessageInfos:      file_dogpb_proto_msgTypes,
	}.Build()
	File_dogpb_proto = out.File
	file_dogpb_proto_rawDesc = nil
	file_dogpb_proto_goTypes = nil
	file_dogpb_proto_depIdxs = nil
}
