// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: emailpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmailListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxType int32 `protobuf:"varint,1,opt,name=box_type,json=boxType,proto3" json:"box_type,omitempty"`
}

func (x *GetEmailListRequest) Reset() {
	*x = GetEmailListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailListRequest) ProtoMessage() {}

func (x *GetEmailListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailListRequest.ProtoReflect.Descriptor instead.
func (*GetEmailListRequest) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmailListRequest) GetBoxType() int32 {
	if x != nil {
		return x.BoxType
	}
	return 0
}

type EmailItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MailType  int32  `protobuf:"varint,2,opt,name=mail_type,json=mailType,proto3" json:"mail_type,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Claimed   bool   `protobuf:"varint,4,opt,name=claimed,proto3" json:"claimed,omitempty"`
	HasReward bool   `protobuf:"varint,5,opt,name=has_reward,json=hasReward,proto3" json:"has_reward,omitempty"`
	Subtitle  string `protobuf:"bytes,7,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
}

func (x *EmailItem) Reset() {
	*x = EmailItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailItem) ProtoMessage() {}

func (x *EmailItem) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailItem.ProtoReflect.Descriptor instead.
func (*EmailItem) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{1}
}

func (x *EmailItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailItem) GetMailType() int32 {
	if x != nil {
		return x.MailType
	}
	return 0
}

func (x *EmailItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmailItem) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *EmailItem) GetHasReward() bool {
	if x != nil {
		return x.HasReward
	}
	return false
}

func (x *EmailItem) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

type GetEmailListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []*EmailItem `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *GetEmailListReply) Reset() {
	*x = GetEmailListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailListReply) ProtoMessage() {}

func (x *GetEmailListReply) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailListReply.ProtoReflect.Descriptor instead.
func (*GetEmailListReply) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmailListReply) GetEmails() []*EmailItem {
	if x != nil {
		return x.Emails
	}
	return nil
}

type ReadEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxType int32  `protobuf:"varint,1,opt,name=box_type,json=boxType,proto3" json:"box_type,omitempty"`
	EmailId string `protobuf:"bytes,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
}

func (x *ReadEmailRequest) Reset() {
	*x = ReadEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEmailRequest) ProtoMessage() {}

func (x *ReadEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEmailRequest.ProtoReflect.Descriptor instead.
func (*ReadEmailRequest) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{3}
}

func (x *ReadEmailRequest) GetBoxType() int32 {
	if x != nil {
		return x.BoxType
	}
	return 0
}

func (x *ReadEmailRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

type ReadEmailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadEmailReply) Reset() {
	*x = ReadEmailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEmailReply) ProtoMessage() {}

func (x *ReadEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEmailReply.ProtoReflect.Descriptor instead.
func (*ReadEmailReply) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{4}
}

type ClaimEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxType int32  `protobuf:"varint,1,opt,name=box_type,json=boxType,proto3" json:"box_type,omitempty"`
	EmailId string `protobuf:"bytes,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
}

func (x *ClaimEmailRequest) Reset() {
	*x = ClaimEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimEmailRequest) ProtoMessage() {}

func (x *ClaimEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimEmailRequest.ProtoReflect.Descriptor instead.
func (*ClaimEmailRequest) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimEmailRequest) GetBoxType() int32 {
	if x != nil {
		return x.BoxType
	}
	return 0
}

func (x *ClaimEmailRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

type ClaimEmailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ClaimEmailReply) Reset() {
	*x = ClaimEmailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimEmailReply) ProtoMessage() {}

func (x *ClaimEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimEmailReply.ProtoReflect.Descriptor instead.
func (*ClaimEmailReply) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimEmailReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchClaimEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxType int32  `protobuf:"varint,1,opt,name=box_type,json=boxType,proto3" json:"box_type,omitempty"`
	EmailId string `protobuf:"bytes,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
}

func (x *BatchClaimEmailRequest) Reset() {
	*x = BatchClaimEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchClaimEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimEmailRequest) ProtoMessage() {}

func (x *BatchClaimEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimEmailRequest.ProtoReflect.Descriptor instead.
func (*BatchClaimEmailRequest) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchClaimEmailRequest) GetBoxType() int32 {
	if x != nil {
		return x.BoxType
	}
	return 0
}

func (x *BatchClaimEmailRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

type BatchClaimEmailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatchClaimEmailReply) Reset() {
	*x = BatchClaimEmailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchClaimEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimEmailReply) ProtoMessage() {}

func (x *BatchClaimEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_emailpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimEmailReply.ProtoReflect.Descriptor instead.
func (*BatchClaimEmailReply) Descriptor() ([]byte, []int) {
	return file_emailpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchClaimEmailReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_emailpb_proto protoreflect.FileDescriptor

var file_emailpb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x70, 0x62, 0x1a,
	0x0c, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xa3, 0x01, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61,
	0x73, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x68, 0x61, 0x73, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x46, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x70, 0x62, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x48, 0x0a,
	0x10, 0x52, 0x65, 0x61, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x49, 0x0a, 0x11, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x62, 0x6f, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x62, 0x6f, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4e, 0x0a, 0x16, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x78, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61,
	0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emailpb_proto_rawDescOnce sync.Once
	file_emailpb_proto_rawDescData = file_emailpb_proto_rawDesc
)

func file_emailpb_proto_rawDescGZIP() []byte {
	file_emailpb_proto_rawDescOnce.Do(func() {
		file_emailpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_emailpb_proto_rawDescData)
	})
	return file_emailpb_proto_rawDescData
}

var file_emailpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_emailpb_proto_goTypes = []interface{}{
	(*GetEmailListRequest)(nil),    // 0: gamepb.emailpb.GetEmailListRequest
	(*EmailItem)(nil),              // 1: gamepb.emailpb.EmailItem
	(*GetEmailListReply)(nil),      // 2: gamepb.emailpb.GetEmailListReply
	(*ReadEmailRequest)(nil),       // 3: gamepb.emailpb.ReadEmailRequest
	(*ReadEmailReply)(nil),         // 4: gamepb.emailpb.ReadEmailReply
	(*ClaimEmailRequest)(nil),      // 5: gamepb.emailpb.ClaimEmailRequest
	(*ClaimEmailReply)(nil),        // 6: gamepb.emailpb.ClaimEmailReply
	(*BatchClaimEmailRequest)(nil), // 7: gamepb.emailpb.BatchClaimEmailRequest
	(*BatchClaimEmailReply)(nil),   // 8: gamepb.emailpb.BatchClaimEmailReply
	(*Item)(nil),                   // 9: corepb.Item
}
var file_emailpb_proto_depIdxs = []int32{
	1, // 0: gamepb.emailpb.GetEmailListReply.emails:type_name -> gamepb.emailpb.EmailItem
	9, // 1: gamepb.emailpb.ClaimEmailReply.items:type_name -> corepb.Item
	9, // 2: gamepb.emailpb.BatchClaimEmailReply.items:type_name -> corepb.Item
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_emailpb_proto_init() }
func file_emailpb_proto_init() {
	if File_emailpb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_emailpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEmailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimEmailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchClaimEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchClaimEmailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emailpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emailpb_proto_goTypes,
		DependencyIndexes: file_emailpb_proto_depIdxs,
		MessageInfos:      file_emailpb_proto_msgTypes,
	}.Build()
	File_emailpb_proto = out.File
	file_emailpb_proto_rawDesc = nil
	file_emailpb_proto_goTypes = nil
	file_emailpb_proto_depIdxs = nil
}
