// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: friendpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 好友农场摘要信息 ============
type Plant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DryTimeSec    int64 `protobuf:"varint,1,opt,name=dry_time_sec,json=dryTimeSec,proto3" json:"dry_time_sec,omitempty"`          // 缺水倒计时秒
	WeedTimeSec   int64 `protobuf:"varint,2,opt,name=weed_time_sec,json=weedTimeSec,proto3" json:"weed_time_sec,omitempty"`       // 长草倒计时秒
	InsectTimeSec int64 `protobuf:"varint,3,opt,name=insect_time_sec,json=insectTimeSec,proto3" json:"insect_time_sec,omitempty"` // 生虫倒计时秒
	RipeTimeSec   int64 `protobuf:"varint,4,opt,name=ripe_time_sec,json=ripeTimeSec,proto3" json:"ripe_time_sec,omitempty"`       // 成熟倒计时秒
	RipeFruitId   int64 `protobuf:"varint,5,opt,name=ripe_fruit_id,json=ripeFruitId,proto3" json:"ripe_fruit_id,omitempty"`       // 成熟果实ID
	StealPlantNum int64 `protobuf:"varint,6,opt,name=steal_plant_num,json=stealPlantNum,proto3" json:"steal_plant_num,omitempty"` // 可偷数量
	DryNum        int64 `protobuf:"varint,7,opt,name=dry_num,json=dryNum,proto3" json:"dry_num,omitempty"`                        // 缺水地块数
	WeedNum       int64 `protobuf:"varint,8,opt,name=weed_num,json=weedNum,proto3" json:"weed_num,omitempty"`                     // 有草地块数
	InsectNum     int64 `protobuf:"varint,9,opt,name=insect_num,json=insectNum,proto3" json:"insect_num,omitempty"`               // 有虫地块数
}

func (x *Plant) Reset() {
	*x = Plant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetDryTimeSec() int64 {
	if x != nil {
		return x.DryTimeSec
	}
	return 0
}

func (x *Plant) GetWeedTimeSec() int64 {
	if x != nil {
		return x.WeedTimeSec
	}
	return 0
}

func (x *Plant) GetInsectTimeSec() int64 {
	if x != nil {
		return x.InsectTimeSec
	}
	return 0
}

func (x *Plant) GetRipeTimeSec() int64 {
	if x != nil {
		return x.RipeTimeSec
	}
	return 0
}

func (x *Plant) GetRipeFruitId() int64 {
	if x != nil {
		return x.RipeFruitId
	}
	return 0
}

func (x *Plant) GetStealPlantNum() int64 {
	if x != nil {
		return x.StealPlantNum
	}
	return 0
}

func (x *Plant) GetDryNum() int64 {
	if x != nil {
		return x.DryNum
	}
	return 0
}

func (x *Plant) GetWeedNum() int64 {
	if x != nil {
		return x.WeedNum
	}
	return 0
}

func (x *Plant) GetInsectNum() int64 {
	if x != nil {
		return x.InsectNum
	}
	return 0
}

// ============ 标签 ============
type Tags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsNew    bool `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsFollow bool `protobuf:"varint,2,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
}

func (x *Tags) Reset() {
	*x = Tags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{1}
}

func (x *Tags) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Tags) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

// ============ 好友信息 ============
type GameFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid              int64  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	OpenId           string `protobuf:"bytes,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name             string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl        string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Remark           string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Level            int64  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Gold             int64  `protobuf:"varint,7,opt,name=gold,proto3" json:"gold,omitempty"`
	Tags             *Tags  `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	Plant            *Plant `protobuf:"bytes,9,opt,name=plant,proto3" json:"plant,omitempty"`
	AuthorizedStatus int32  `protobuf:"varint,10,opt,name=authorized_status,json=authorizedStatus,proto3" json:"authorized_status,omitempty"`
}

func (x *GameFriend) Reset() {
	*x = GameFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFriend) ProtoMessage() {}

func (x *GameFriend) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFriend.ProtoReflect.Descriptor instead.
func (*GameFriend) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{2}
}

func (x *GameFriend) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GameFriend) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *GameFriend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameFriend) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GameFriend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GameFriend) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameFriend) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GameFriend) GetTags() *Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GameFriend) GetPlant() *Plant {
	if x != nil {
		return x.Plant
	}
	return nil
}

func (x *GameFriend) GetAuthorizedStatus() int32 {
	if x != nil {
		return x.AuthorizedStatus
	}
	return 0
}

// --- 获取所有好友 ---
type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{3}
}

type GetAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameFriends []*GameFriend `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	// repeated Invitation invitations = 2;  // 略
	ApplicationCount int64 `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *GetAllReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

// --- 获取指定游戏好友 (通过GID列表) ---
type GetGameFriendsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gids []int64 `protobuf:"varint,1,rep,packed,name=gids,proto3" json:"gids,omitempty"`
}

func (x *GetGameFriendsRequest) Reset() {
	*x = GetGameFriendsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameFriendsRequest) ProtoMessage() {}

func (x *GetGameFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetGameFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameFriendsRequest) GetGids() []int64 {
	if x != nil {
		return x.Gids
	}
	return nil
}

// --- 同步好友 (带 open_ids) ---
type SyncAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// field 1 reserved
	OpenIds []string `protobuf:"bytes,2,rep,name=open_ids,json=openIds,proto3" json:"open_ids,omitempty"`
}

func (x *SyncAllRequest) Reset() {
	*x = SyncAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllRequest) ProtoMessage() {}

func (x *SyncAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllRequest.ProtoReflect.Descriptor instead.
func (*SyncAllRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{6}
}

func (x *SyncAllRequest) GetOpenIds() []string {
	if x != nil {
		return x.OpenIds
	}
	return nil
}

type SyncAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameFriends []*GameFriend `protobuf:"bytes,1,rep,name=game_friends,json=gameFriends,proto3" json:"game_friends,omitempty"`
	// repeated Invitation invitations = 2;  // 略
	ApplicationCount int64 `protobuf:"varint,3,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
}

func (x *SyncAllReply) Reset() {
	*x = SyncAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllReply) ProtoMessage() {}

func (x *SyncAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllReply.ProtoReflect.Descriptor instead.
func (*SyncAllReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{7}
}

func (x *SyncAllReply) GetGameFriends() []*GameFriend {
	if x != nil {
		return x.GameFriends
	}
	return nil
}

func (x *SyncAllReply) GetApplicationCount() int64 {
	if x != nil {
		return x.ApplicationCount
	}
	return 0
}

// 申请信息
type Application struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid       int64  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	TimeAt    int64  `protobuf:"varint,2,opt,name=time_at,json=timeAt,proto3" json:"time_at,omitempty"`
	OpenId    string `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Level     int64  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"` // repeated AvatarFrame equip_avatar_frames = 7;  // 略
}

func (x *Application) Reset() {
	*x = Application{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{8}
}

func (x *Application) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Application) GetTimeAt() int64 {
	if x != nil {
		return x.TimeAt
	}
	return 0
}

func (x *Application) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Application) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

// --- 获取好友申请列表 ---
type GetApplicationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetApplicationsRequest) Reset() {
	*x = GetApplicationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsRequest) ProtoMessage() {}

func (x *GetApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{9}
}

type GetApplicationsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Applications      []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	BlockApplications bool           `protobuf:"varint,2,opt,name=block_applications,json=blockApplications,proto3" json:"block_applications,omitempty"` // 是否屏蔽申请
}

func (x *GetApplicationsReply) Reset() {
	*x = GetApplicationsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsReply) ProtoMessage() {}

func (x *GetApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsReply.ProtoReflect.Descriptor instead.
func (*GetApplicationsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{10}
}

func (x *GetApplicationsReply) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *GetApplicationsReply) GetBlockApplications() bool {
	if x != nil {
		return x.BlockApplications
	}
	return false
}

// --- 同意好友申请 ---
type AcceptFriendsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendGids []int64 `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
}

func (x *AcceptFriendsRequest) Reset() {
	*x = AcceptFriendsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendsRequest) ProtoMessage() {}

func (x *AcceptFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendsRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type AcceptFriendsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*GameFriend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
}

func (x *AcceptFriendsReply) Reset() {
	*x = AcceptFriendsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendsReply) ProtoMessage() {}

func (x *AcceptFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendsReply.ProtoReflect.Descriptor instead.
func (*AcceptFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptFriendsReply) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

// --- 拒绝好友申请 ---
type RejectFriendsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendGids []int64 `protobuf:"varint,1,rep,packed,name=friend_gids,json=friendGids,proto3" json:"friend_gids,omitempty"`
}

func (x *RejectFriendsRequest) Reset() {
	*x = RejectFriendsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendsRequest) ProtoMessage() {}

func (x *RejectFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendsRequest.ProtoReflect.Descriptor instead.
func (*RejectFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{13}
}

func (x *RejectFriendsRequest) GetFriendGids() []int64 {
	if x != nil {
		return x.FriendGids
	}
	return nil
}

type RejectFriendsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RejectFriendsReply) Reset() {
	*x = RejectFriendsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendsReply) ProtoMessage() {}

func (x *RejectFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendsReply.ProtoReflect.Descriptor instead.
func (*RejectFriendsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{14}
}

// --- 删除好友 ---
// 抓包样例: gamepb.friendpb.FriendService.DelFriend
type DelFriendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendGid int64 `protobuf:"varint,1,opt,name=friend_gid,json=friendGid,proto3" json:"friend_gid,omitempty"`
}

func (x *DelFriendRequest) Reset() {
	*x = DelFriendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFriendRequest) ProtoMessage() {}

func (x *DelFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFriendRequest.ProtoReflect.Descriptor instead.
func (*DelFriendRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{15}
}

func (x *DelFriendRequest) GetFriendGid() int64 {
	if x != nil {
		return x.FriendGid
	}
	return 0
}

type DelFriendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelFriendReply) Reset() {
	*x = DelFriendReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFriendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFriendReply) ProtoMessage() {}

func (x *DelFriendReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFriendReply.ProtoReflect.Descriptor instead.
func (*DelFriendReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{16}
}

// --- 主动发送好友申请 ---
// 抓包样例: gamepb.friendpb.FriendService.ApplyFriend
// 【2026-07-25 经 TSDK 解密抓包逐字节还原】真实结构为:
//
//	field1 (varint) = 目标 gid
//	field2 (string, 75B) = "<64hex token>:<gid>"，其中 token = SHA256("<hex32>:<gid>")
//	  hex32 是 32 位十六进制的客户端会话 nonce，需在前置 Enter 请求 field7 中带上同一值。
//
// 业务体不含 openid。
type ApplyFriendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid   int64  `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`    // 目标 gid
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // "<sha256(hex32:gid)>:<gid>"
}

func (x *ApplyFriendRequest) Reset() {
	*x = ApplyFriendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendRequest) ProtoMessage() {}

func (x *ApplyFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendRequest.ProtoReflect.Descriptor instead.
func (*ApplyFriendRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyFriendRequest) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ApplyFriendRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ApplyFriendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyFriendReply) Reset() {
	*x = ApplyFriendReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyFriendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendReply) ProtoMessage() {}

func (x *ApplyFriendReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendReply.ProtoReflect.Descriptor instead.
func (*ApplyFriendReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{18}
}

// --- 设置屏蔽申请 ---
type SetBlockApplicationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block bool `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *SetBlockApplicationsRequest) Reset() {
	*x = SetBlockApplicationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBlockApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockApplicationsRequest) ProtoMessage() {}

func (x *SetBlockApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockApplicationsRequest.ProtoReflect.Descriptor instead.
func (*SetBlockApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{19}
}

func (x *SetBlockApplicationsRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type SetBlockApplicationsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block bool `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *SetBlockApplicationsReply) Reset() {
	*x = SetBlockApplicationsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBlockApplicationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBlockApplicationsReply) ProtoMessage() {}

func (x *SetBlockApplicationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBlockApplicationsReply.ProtoReflect.Descriptor instead.
func (*SetBlockApplicationsReply) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{20}
}

func (x *SetBlockApplicationsReply) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

// 收到好友申请通知
type FriendApplicationReceivedNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Applications []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
}

func (x *FriendApplicationReceivedNotify) Reset() {
	*x = FriendApplicationReceivedNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendApplicationReceivedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplicationReceivedNotify) ProtoMessage() {}

func (x *FriendApplicationReceivedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplicationReceivedNotify.ProtoReflect.Descriptor instead.
func (*FriendApplicationReceivedNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{21}
}

func (x *FriendApplicationReceivedNotify) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

// 好友添加成功通知 (对方同意后)
type FriendAddedNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*GameFriend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
}

func (x *FriendAddedNotify) Reset() {
	*x = FriendAddedNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friendpb_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendAddedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddedNotify) ProtoMessage() {}

func (x *FriendAddedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_friendpb_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddedNotify.ProtoReflect.Descriptor instead.
func (*FriendAddedNotify) Descriptor() ([]byte, []int) {
	return file_friendpb_proto_rawDescGZIP(), []int{22}
}

func (x *FriendAddedNotify) GetFriends() []*GameFriend {
	if x != nil {
		return x.Friends
	}
	return nil
}

var File_friendpb_proto protoreflect.FileDescriptor

var file_friendpb_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x70,
	0x62, 0x22, 0xb8, 0x02, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x64,
	0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x64, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x22, 0x0a,
	0x0d, 0x77, 0x65, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x77, 0x65, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65,
	0x63, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x73, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x65,
	0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x69, 0x70,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x72, 0x69, 0x70, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x22, 0x0a,
	0x0d, 0x72, 0x69, 0x70, 0x65, 0x5f, 0x66, 0x72, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x69, 0x70, 0x65, 0x46, 0x72, 0x75, 0x69, 0x74, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x74, 0x65, 0x61, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x74, 0x65, 0x61,
	0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x72, 0x79,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x72, 0x79, 0x4e,
	0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x65, 0x65, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x77, 0x65, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x04,
	0x54, 0x61, 0x67, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x69, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x22, 0xb2, 0x02, 0x0a, 0x0a, 0x47, 0x61, 0x6d,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74,
	0x12, 0x2b, 0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7a,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a,
	0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x2b, 0x0a,
	0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x04, 0x67, 0x69, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x73, 0x22, 0x7b, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x9a, 0x01, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x67, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x18,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x40, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62,
	0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x37, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x69, 0x64, 0x73, 0x22, 0x4b, 0x0a, 0x12, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x35, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x22, 0x37, 0x0a, 0x14, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x69, 0x64,
	0x73, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x31, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3c, 0x0a, 0x12,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x67, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x33,
	0x0a, 0x1b, 0x53, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x22, 0x31, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x63, 0x0a, 0x1f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x40, 0x0a, 0x0c, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x70,
	0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x11, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x35, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x70, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x07,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61,
	0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_friendpb_proto_rawDescOnce sync.Once
	file_friendpb_proto_rawDescData = file_friendpb_proto_rawDesc
)

func file_friendpb_proto_rawDescGZIP() []byte {
	file_friendpb_proto_rawDescOnce.Do(func() {
		file_friendpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_friendpb_proto_rawDescData)
	})
	return file_friendpb_proto_rawDescData
}

var file_friendpb_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_friendpb_proto_goTypes = []interface{}{
	(*Plant)(nil),                           // 0: gamepb.friendpb.Plant
	(*Tags)(nil),                            // 1: gamepb.friendpb.Tags
	(*GameFriend)(nil),                      // 2: gamepb.friendpb.GameFriend
	(*GetAllRequest)(nil),                   // 3: gamepb.friendpb.GetAllRequest
	(*GetAllReply)(nil),                     // 4: gamepb.friendpb.GetAllReply
	(*GetGameFriendsRequest)(nil),           // 5: gamepb.friendpb.GetGameFriendsRequest
	(*SyncAllRequest)(nil),                  // 6: gamepb.friendpb.SyncAllRequest
	(*SyncAllReply)(nil),                    // 7: gamepb.friendpb.SyncAllReply
	(*Application)(nil),                     // 8: gamepb.friendpb.Application
	(*GetApplicationsRequest)(nil),          // 9: gamepb.friendpb.GetApplicationsRequest
	(*GetApplicationsReply)(nil),            // 10: gamepb.friendpb.GetApplicationsReply
	(*AcceptFriendsRequest)(nil),            // 11: gamepb.friendpb.AcceptFriendsRequest
	(*AcceptFriendsReply)(nil),              // 12: gamepb.friendpb.AcceptFriendsReply
	(*RejectFriendsRequest)(nil),            // 13: gamepb.friendpb.RejectFriendsRequest
	(*RejectFriendsReply)(nil),              // 14: gamepb.friendpb.RejectFriendsReply
	(*DelFriendRequest)(nil),                // 15: gamepb.friendpb.DelFriendRequest
	(*DelFriendReply)(nil),                  // 16: gamepb.friendpb.DelFriendReply
	(*ApplyFriendRequest)(nil),              // 17: gamepb.friendpb.ApplyFriendRequest
	(*ApplyFriendReply)(nil),                // 18: gamepb.friendpb.ApplyFriendReply
	(*SetBlockApplicationsRequest)(nil),     // 19: gamepb.friendpb.SetBlockApplicationsRequest
	(*SetBlockApplicationsReply)(nil),       // 20: gamepb.friendpb.SetBlockApplicationsReply
	(*FriendApplicationReceivedNotify)(nil), // 21: gamepb.friendpb.FriendApplicationReceivedNotify
	(*FriendAddedNotify)(nil),               // 22: gamepb.friendpb.FriendAddedNotify
}
var file_friendpb_proto_depIdxs = []int32{
	1, // 0: gamepb.friendpb.GameFriend.tags:type_name -> gamepb.friendpb.Tags
	0, // 1: gamepb.friendpb.GameFriend.plant:type_name -> gamepb.friendpb.Plant
	2, // 2: gamepb.friendpb.GetAllReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	2, // 3: gamepb.friendpb.SyncAllReply.game_friends:type_name -> gamepb.friendpb.GameFriend
	8, // 4: gamepb.friendpb.GetApplicationsReply.applications:type_name -> gamepb.friendpb.Application
	2, // 5: gamepb.friendpb.AcceptFriendsReply.friends:type_name -> gamepb.friendpb.GameFriend
	8, // 6: gamepb.friendpb.FriendApplicationReceivedNotify.applications:type_name -> gamepb.friendpb.Application
	2, // 7: gamepb.friendpb.FriendAddedNotify.friends:type_name -> gamepb.friendpb.GameFriend
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_friendpb_proto_init() }
func file_friendpb_proto_init() {
	if File_friendpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_friendpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameFriendsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Application); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicationsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptFriendsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptFriendsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectFriendsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectFriendsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFriendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFriendReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyFriendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyFriendReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBlockApplicationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBlockApplicationsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendApplicationReceivedNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friendpb_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendAddedNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friendpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friendpb_proto_goTypes,
		DependencyIndexes: file_friendpb_proto_depIdxs,
		MessageInfos:      file_friendpb_proto_msgTypes,
	}.Build()
	File_friendpb_proto = out.File
	file_friendpb_proto_rawDesc = nil
	file_friendpb_proto_goTypes = nil
	file_friendpb_proto_depIdxs = nil
}
