// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: interactpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime int64                 `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ActionType int32                 `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	VisitorGid int64                 `protobuf:"varint,3,opt,name=visitor_gid,json=visitorGid,proto3" json:"visitor_gid,omitempty"`
	Nick       string                `protobuf:"bytes,4,opt,name=nick,proto3" json:"nick,omitempty"`
	AvatarUrl  string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CropId     int32                 `protobuf:"varint,6,opt,name=crop_id,json=cropId,proto3" json:"crop_id,omitempty"`
	CropCount  int32                 `protobuf:"varint,7,opt,name=crop_count,json=cropCount,proto3" json:"crop_count,omitempty"`
	Times      int32                 `protobuf:"varint,8,opt,name=times,proto3" json:"times,omitempty"`
	FromType   int32                 `protobuf:"varint,9,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	Level      int32                 `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Extra      *InteractRecord_Extra `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *InteractRecord) Reset() {
	*x = InteractRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interactpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecord) ProtoMessage() {}

func (x *InteractRecord) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecord.ProtoReflect.Descriptor instead.
func (*InteractRecord) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{0}
}

func (x *InteractRecord) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *InteractRecord) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *InteractRecord) GetVisitorGid() int64 {
	if x != nil {
		return x.VisitorGid
	}
	return 0
}

func (x *InteractRecord) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *InteractRecord) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *InteractRecord) GetCropId() int32 {
	if x != nil {
		return x.CropId
	}
	return 0
}

func (x *InteractRecord) GetCropCount() int32 {
	if x != nil {
		return x.CropCount
	}
	return 0
}

func (x *InteractRecord) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *InteractRecord) GetFromType() int32 {
	if x != nil {
		return x.FromType
	}
	return 0
}

func (x *InteractRecord) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *InteractRecord) GetExtra() *InteractRecord_Extra {
	if x != nil {
		return x.Extra
	}
	return nil
}

type InteractRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InteractRecordsRequest) Reset() {
	*x = InteractRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interactpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecordsRequest) ProtoMessage() {}

func (x *InteractRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecordsRequest.ProtoReflect.Descriptor instead.
func (*InteractRecordsRequest) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{1}
}

type InteractRecordsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*InteractRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *InteractRecordsReply) Reset() {
	*x = InteractRecordsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interactpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractRecordsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecordsReply) ProtoMessage() {}

func (x *InteractRecordsReply) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecordsReply.ProtoReflect.Descriptor instead.
func (*InteractRecordsReply) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{2}
}

func (x *InteractRecordsReply) GetRecords() []*InteractRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type InteractRecord_Extra struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LandId int32 `protobuf:"varint,1,opt,name=land_id,json=landId,proto3" json:"land_id,omitempty"`
	Flag1  int32 `protobuf:"varint,2,opt,name=flag1,proto3" json:"flag1,omitempty"`
	Flag2  int32 `protobuf:"varint,3,opt,name=flag2,proto3" json:"flag2,omitempty"`
}

func (x *InteractRecord_Extra) Reset() {
	*x = InteractRecord_Extra{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interactpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractRecord_Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRecord_Extra) ProtoMessage() {}

func (x *InteractRecord_Extra) ProtoReflect() protoreflect.Message {
	mi := &file_interactpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRecord_Extra.ProtoReflect.Descriptor instead.
func (*InteractRecord_Extra) Descriptor() ([]byte, []int) {
	return file_interactpb_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InteractRecord_Extra) GetLandId() int32 {
	if x != nil {
		return x.LandId
	}
	return 0
}

func (x *InteractRecord_Extra) GetFlag1() int32 {
	if x != nil {
		return x.Flag1
	}
	return 0
}

func (x *InteractRecord_Extra) GetFlag2() int32 {
	if x != nil {
		return x.Flag2
	}
	return 0
}

var File_interactpb_proto protoreflect.FileDescriptor

var file_interactpb_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x70, 0x62, 0x22, 0xb4, 0x03, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x69,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x47, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x69, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x63, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x6f, 0x70, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x6f,
	0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x3d, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x4c,
	0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x6e, 0x64, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x66, 0x6c, 0x61, 0x67, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x32, 0x22, 0x18, 0x0a, 0x16,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68,
	0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interactpb_proto_rawDescOnce sync.Once
	file_interactpb_proto_rawDescData = file_interactpb_proto_rawDesc
)

func file_interactpb_proto_rawDescGZIP() []byte {
	file_interactpb_proto_rawDescOnce.Do(func() {
		file_interactpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_interactpb_proto_rawDescData)
	})
	return file_interactpb_proto_rawDescData
}

var file_interactpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_interactpb_proto_goTypes = []interface{}{
	(*InteractRecord)(nil),         // 0: gamepb.interactpb.InteractRecord
	(*InteractRecordsRequest)(nil), // 1: gamepb.interactpb.InteractRecordsRequest
	(*InteractRecordsReply)(nil),   // 2: gamepb.interactpb.InteractRecordsReply
	(*InteractRecord_Extra)(nil),   // 3: gamepb.interactpb.InteractRecord.Extra
}
var file_interactpb_proto_depIdxs = []int32{
	3, // 0: gamepb.interactpb.InteractRecord.extra:type_name -> gamepb.interactpb.InteractRecord.Extra
	0, // 1: gamepb.interactpb.InteractRecordsReply.records:type_name -> gamepb.interactpb.InteractRecord
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_interactpb_proto_init() }
func file_interactpb_proto_init() {
	if File_interactpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interactpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interactpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interactpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractRecordsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interactpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractRecord_Extra); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interactpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interactpb_proto_goTypes,
		DependencyIndexes: file_interactpb_proto_depIdxs,
		MessageInfos:      file_interactpb_proto_msgTypes,
	}.Build()
	File_interactpb_proto = out.File
	file_interactpb_proto_rawDesc = nil
	file_interactpb_proto_goTypes = nil
	file_interactpb_proto_depIdxs = nil
}
