// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: itempb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取背包
type BagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BagRequest) Reset() {
	*x = BagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagRequest) ProtoMessage() {}

func (x *BagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagRequest.ProtoReflect.Descriptor instead.
func (*BagRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{0}
}

type BagReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemBag *ItemBag `protobuf:"bytes,1,opt,name=item_bag,json=itemBag,proto3" json:"item_bag,omitempty"` // 与 game 一致，背包数据在 item_bag 里
}

func (x *BagReply) Reset() {
	*x = BagReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagReply) ProtoMessage() {}

func (x *BagReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagReply.ProtoReflect.Descriptor instead.
func (*BagReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{1}
}

func (x *BagReply) GetItemBag() *ItemBag {
	if x != nil {
		return x.ItemBag
	}
	return nil
}

type SellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 要出售的物品列表 (id + count)
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{2}
}

func (x *SellRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SellReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SellItems []*Item `protobuf:"bytes,1,rep,name=sell_items,json=sellItems,proto3" json:"sell_items,omitempty"` // 出售的物品
	GetItems  []*Item `protobuf:"bytes,2,rep,name=get_items,json=getItems,proto3" json:"get_items,omitempty"`    // 获得的物品（常见: 1001=金币, 1002=点券）
}

func (x *SellReply) Reset() {
	*x = SellReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellReply) ProtoMessage() {}

func (x *SellReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellReply.ProtoReflect.Descriptor instead.
func (*SellReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{3}
}

func (x *SellReply) GetSellItems() []*Item {
	if x != nil {
		return x.SellItems
	}
	return nil
}

func (x *SellReply) GetGetItems() []*Item {
	if x != nil {
		return x.GetItems
	}
	return nil
}

type UseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId  int64   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count   int64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LandIds []int64 `protobuf:"varint,3,rep,packed,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
}

func (x *UseRequest) Reset() {
	*x = UseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseRequest) ProtoMessage() {}

func (x *UseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseRequest.ProtoReflect.Descriptor instead.
func (*UseRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{4}
}

func (x *UseRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UseRequest) GetLandIds() []int64 {
	if x != nil {
		return x.LandIds
	}
	return nil
}

type UseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UseReply) Reset() {
	*x = UseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseReply) ProtoMessage() {}

func (x *UseReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseReply.ProtoReflect.Descriptor instead.
func (*UseReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{5}
}

func (x *UseReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchUseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatchUseRequest) Reset() {
	*x = BatchUseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUseRequest) ProtoMessage() {}

func (x *BatchUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUseRequest.ProtoReflect.Descriptor instead.
func (*BatchUseRequest) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchUseRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchUseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsedItems []*Item `protobuf:"bytes,1,rep,name=used_items,json=usedItems,proto3" json:"used_items,omitempty"`
	Items     []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatchUseReply) Reset() {
	*x = BatchUseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itempb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUseReply) ProtoMessage() {}

func (x *BatchUseReply) ProtoReflect() protoreflect.Message {
	mi := &file_itempb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUseReply.ProtoReflect.Descriptor instead.
func (*BatchUseReply) Descriptor() ([]byte, []int) {
	return file_itempb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchUseReply) GetUsedItems() []*Item {
	if x != nil {
		return x.UsedItems
	}
	return nil
}

func (x *BatchUseReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_itempb_proto protoreflect.FileDescriptor

var file_itempb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x42,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x42, 0x61, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x62, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x67, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x42, 0x61,
	0x67, 0x22, 0x31, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x63, 0x0a, 0x09, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2b, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x29,
	0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x08, 0x67, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x6e, 0x64, 0x49, 0x64,
	0x73, 0x22, 0x2e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x35, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x60, 0x0a, 0x0d, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x55, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c,
	0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itempb_proto_rawDescOnce sync.Once
	file_itempb_proto_rawDescData = file_itempb_proto_rawDesc
)

func file_itempb_proto_rawDescGZIP() []byte {
	file_itempb_proto_rawDescOnce.Do(func() {
		file_itempb_proto_rawDescData = protoimpl.X.CompressGZIP(file_itempb_proto_rawDescData)
	})
	return file_itempb_proto_rawDescData
}

var file_itempb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_itempb_proto_goTypes = []interface{}{
	(*BagRequest)(nil),      // 0: gamepb.itempb.BagRequest
	(*BagReply)(nil),        // 1: gamepb.itempb.BagReply
	(*SellRequest)(nil),     // 2: gamepb.itempb.SellRequest
	(*SellReply)(nil),       // 3: gamepb.itempb.SellReply
	(*UseRequest)(nil),      // 4: gamepb.itempb.UseRequest
	(*UseReply)(nil),        // 5: gamepb.itempb.UseReply
	(*BatchUseRequest)(nil), // 6: gamepb.itempb.BatchUseRequest
	(*BatchUseReply)(nil),   // 7: gamepb.itempb.BatchUseReply
	(*ItemBag)(nil),         // 8: corepb.ItemBag
	(*Item)(nil),            // 9: corepb.Item
}
var file_itempb_proto_depIdxs = []int32{
	8, // 0: gamepb.itempb.BagReply.item_bag:type_name -> corepb.ItemBag
	9, // 1: gamepb.itempb.SellRequest.items:type_name -> corepb.Item
	9, // 2: gamepb.itempb.SellReply.sell_items:type_name -> corepb.Item
	9, // 3: gamepb.itempb.SellReply.get_items:type_name -> corepb.Item
	9, // 4: gamepb.itempb.UseReply.items:type_name -> corepb.Item
	9, // 5: gamepb.itempb.BatchUseRequest.items:type_name -> corepb.Item
	9, // 6: gamepb.itempb.BatchUseReply.used_items:type_name -> corepb.Item
	9, // 7: gamepb.itempb.BatchUseReply.items:type_name -> corepb.Item
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_itempb_proto_init() }
func file_itempb_proto_init() {
	if File_itempb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_itempb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itempb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itempb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itempb_proto_goTypes,
		DependencyIndexes: file_itempb_proto_depIdxs,
		MessageInfos:      file_itempb_proto_msgTypes,
	}.Build()
	File_itempb_proto = out.File
	file_itempb_proto_rawDesc = nil
	file_itempb_proto_goTypes = nil
	file_itempb_proto_depIdxs = nil
}
