// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: mallpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取商场列表请求
type GetMallListBySlotTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotType int32 `protobuf:"varint,1,opt,name=slot_type,json=slotType,proto3" json:"slot_type,omitempty"` // 商场类型
}

func (x *GetMallListBySlotTypeRequest) Reset() {
	*x = GetMallListBySlotTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMallListBySlotTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMallListBySlotTypeRequest) ProtoMessage() {}

func (x *GetMallListBySlotTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMallListBySlotTypeRequest.ProtoReflect.Descriptor instead.
func (*GetMallListBySlotTypeRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetMallListBySlotTypeRequest) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

// 获取商场列表响应
type GetMallListBySlotTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsList [][]byte `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"` // 商品列表（每个是序列化的MallGoods）
	Timestamp int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳
}

func (x *GetMallListBySlotTypeResponse) Reset() {
	*x = GetMallListBySlotTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMallListBySlotTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMallListBySlotTypeResponse) ProtoMessage() {}

func (x *GetMallListBySlotTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMallListBySlotTypeResponse.ProtoReflect.Descriptor instead.
func (*GetMallListBySlotTypeResponse) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetMallListBySlotTypeResponse) GetGoodsList() [][]byte {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

func (x *GetMallListBySlotTypeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 商品信息
type MallGoods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId   int32  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`       // 商品ID
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 商品名称
	Type      int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                            // 商品类型
	ItemIds   []byte `protobuf:"bytes,4,opt,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`        // 物品ID列表（序列化数据）
	Price     []byte `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`                           // 价格（序列化数据）
	IsFree    bool   `protobuf:"varint,6,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`          // 是否免费
	Limit     []byte `protobuf:"bytes,7,opt,name=limit,proto3" json:"limit,omitempty"`                           // 限购信息（序列化数据）
	IsLimited bool   `protobuf:"varint,8,opt,name=is_limited,json=isLimited,proto3" json:"is_limited,omitempty"` // 是否限购
	Discount  string `protobuf:"bytes,10,opt,name=discount,proto3" json:"discount,omitempty"`                    // 折扣信息
}

func (x *MallGoods) Reset() {
	*x = MallGoods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MallGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallGoods) ProtoMessage() {}

func (x *MallGoods) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallGoods.ProtoReflect.Descriptor instead.
func (*MallGoods) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{2}
}

func (x *MallGoods) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *MallGoods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MallGoods) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MallGoods) GetItemIds() []byte {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *MallGoods) GetPrice() []byte {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *MallGoods) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *MallGoods) GetLimit() []byte {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *MallGoods) GetIsLimited() bool {
	if x != nil {
		return x.IsLimited
	}
	return false
}

func (x *MallGoods) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

// 购买请求
type PurchaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
	Count   int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                    // 购买数量
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{3}
}

func (x *PurchaseRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *PurchaseRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 购买响应
type PurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId    int32  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`         // 商品ID
	Count      int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                            // 购买数量
	RewardInfo []byte `protobuf:"bytes,3,opt,name=reward_info,json=rewardInfo,proto3" json:"reward_info,omitempty"` // 奖励信息
	Result     []byte `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`                           // 购买结果
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *PurchaseResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PurchaseResponse) GetRewardInfo() []byte {
	if x != nil {
		return x.RewardInfo
	}
	return nil
}

func (x *PurchaseResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// 月卡信息
type GetMonthCardInfosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMonthCardInfosRequest) Reset() {
	*x = GetMonthCardInfosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMonthCardInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthCardInfosRequest) ProtoMessage() {}

func (x *GetMonthCardInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthCardInfosRequest.ProtoReflect.Descriptor instead.
func (*GetMonthCardInfosRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{5}
}

type MonthCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId  int32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Reward   *Item `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward,omitempty"`
	CanClaim bool  `protobuf:"varint,3,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
}

func (x *MonthCardInfo) Reset() {
	*x = MonthCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthCardInfo) ProtoMessage() {}

func (x *MonthCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthCardInfo.ProtoReflect.Descriptor instead.
func (*MonthCardInfo) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{6}
}

func (x *MonthCardInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *MonthCardInfo) GetReward() *Item {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *MonthCardInfo) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

type GetMonthCardInfosReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*MonthCardInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *GetMonthCardInfosReply) Reset() {
	*x = GetMonthCardInfosReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMonthCardInfosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthCardInfosReply) ProtoMessage() {}

func (x *GetMonthCardInfosReply) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthCardInfosReply.ProtoReflect.Descriptor instead.
func (*GetMonthCardInfosReply) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{7}
}

func (x *GetMonthCardInfosReply) GetInfos() []*MonthCardInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 领取月卡奖励
type ClaimMonthCardRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
}

func (x *ClaimMonthCardRewardRequest) Reset() {
	*x = ClaimMonthCardRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimMonthCardRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMonthCardRewardRequest) ProtoMessage() {}

func (x *ClaimMonthCardRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMonthCardRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimMonthCardRewardRequest) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimMonthCardRewardRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type ClaimMonthCardRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ClaimMonthCardRewardReply) Reset() {
	*x = ClaimMonthCardRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mallpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimMonthCardRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMonthCardRewardReply) ProtoMessage() {}

func (x *ClaimMonthCardRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_mallpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMonthCardRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimMonthCardRewardReply) Descriptor() ([]byte, []int) {
	return file_mallpb_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimMonthCardRewardReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_mallpb_proto protoreflect.FileDescriptor

var file_mallpb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x1a, 0x0c, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x6c, 0x6f, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x6c, 0x6f, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5c, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xe9, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x6c, 0x6c, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x66,
	0x72, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x46, 0x72, 0x65,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x42, 0x0a, 0x0f, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7c, 0x0a, 0x10, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x6d, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x06,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x22,
	0x4c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70,
	0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61,
	0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x38, 0x0a,
	0x1b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x19, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xa1, 0x03, 0x0a, 0x0b, 0x4d, 0x61, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x2b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53,
	0x6c, 0x6f, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x6c, 0x6f, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x08,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70,
	0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70,
	0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x27,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62,
	0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6c,
	0x0a, 0x14, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x2a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e,
	0x6d, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x6f, 0x6e, 0x74,
	0x68, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x6c, 0x6c,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b,
	0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mallpb_proto_rawDescOnce sync.Once
	file_mallpb_proto_rawDescData = file_mallpb_proto_rawDesc
)

func file_mallpb_proto_rawDescGZIP() []byte {
	file_mallpb_proto_rawDescOnce.Do(func() {
		file_mallpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_mallpb_proto_rawDescData)
	})
	return file_mallpb_proto_rawDescData
}

var file_mallpb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mallpb_proto_goTypes = []interface{}{
	(*GetMallListBySlotTypeRequest)(nil),  // 0: gamepb.mallpb.GetMallListBySlotTypeRequest
	(*GetMallListBySlotTypeResponse)(nil), // 1: gamepb.mallpb.GetMallListBySlotTypeResponse
	(*MallGoods)(nil),                     // 2: gamepb.mallpb.MallGoods
	(*PurchaseRequest)(nil),               // 3: gamepb.mallpb.PurchaseRequest
	(*PurchaseResponse)(nil),              // 4: gamepb.mallpb.PurchaseResponse
	(*GetMonthCardInfosRequest)(nil),      // 5: gamepb.mallpb.GetMonthCardInfosRequest
	(*MonthCardInfo)(nil),                 // 6: gamepb.mallpb.MonthCardInfo
	(*GetMonthCardInfosReply)(nil),        // 7: gamepb.mallpb.GetMonthCardInfosReply
	(*ClaimMonthCardRewardRequest)(nil),   // 8: gamepb.mallpb.ClaimMonthCardRewardRequest
	(*ClaimMonthCardRewardReply)(nil),     // 9: gamepb.mallpb.ClaimMonthCardRewardReply
	(*Item)(nil),                          // 10: corepb.Item
}
var file_mallpb_proto_depIdxs = []int32{
	10, // 0: gamepb.mallpb.MonthCardInfo.reward:type_name -> corepb.Item
	6,  // 1: gamepb.mallpb.GetMonthCardInfosReply.infos:type_name -> gamepb.mallpb.MonthCardInfo
	10, // 2: gamepb.mallpb.ClaimMonthCardRewardReply.items:type_name -> corepb.Item
	0,  // 3: gamepb.mallpb.MallService.GetMallListBySlotType:input_type -> gamepb.mallpb.GetMallListBySlotTypeRequest
	3,  // 4: gamepb.mallpb.MallService.Purchase:input_type -> gamepb.mallpb.PurchaseRequest
	5,  // 5: gamepb.mallpb.MallService.GetMonthCardInfos:input_type -> gamepb.mallpb.GetMonthCardInfosRequest
	8,  // 6: gamepb.mallpb.MallService.ClaimMonthCardReward:input_type -> gamepb.mallpb.ClaimMonthCardRewardRequest
	1,  // 7: gamepb.mallpb.MallService.GetMallListBySlotType:output_type -> gamepb.mallpb.GetMallListBySlotTypeResponse
	4,  // 8: gamepb.mallpb.MallService.Purchase:output_type -> gamepb.mallpb.PurchaseResponse
	7,  // 9: gamepb.mallpb.MallService.GetMonthCardInfos:output_type -> gamepb.mallpb.GetMonthCardInfosReply
	9,  // 10: gamepb.mallpb.MallService.ClaimMonthCardReward:output_type -> gamepb.mallpb.ClaimMonthCardRewardReply
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mallpb_proto_init() }
func file_mallpb_proto_init() {
	if File_mallpb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mallpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMallListBySlotTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMallListBySlotTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MallGoods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMonthCardInfosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMonthCardInfosReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimMonthCardRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mallpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimMonthCardRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mallpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mallpb_proto_goTypes,
		DependencyIndexes: file_mallpb_proto_depIdxs,
		MessageInfos:      file_mallpb_proto_msgTypes,
	}.Build()
	File_mallpb_proto = out.File
	file_mallpb_proto_rawDesc = nil
	file_mallpb_proto_goTypes = nil
	file_mallpb_proto_depIdxs = nil
}
