// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: mysteryshoppb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActiveNPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetActiveNPCRequest) Reset() {
	*x = GetActiveNPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveNPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveNPCRequest) ProtoMessage() {}

func (x *GetActiveNPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveNPCRequest.ProtoReflect.Descriptor instead.
func (*GetActiveNPCRequest) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{0}
}

type MysteryShopNPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NpcId         int64 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	ItemId        int32 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      int32 `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	ItemCount     int32 `protobuf:"varint,4,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	CurrencyId    int32 `protobuf:"varint,5,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Price         int64 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Discount      int32 `protobuf:"varint,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Purchased     bool  `protobuf:"varint,8,opt,name=purchased,proto3" json:"purchased,omitempty"`
	OriginalPrice int64 `protobuf:"varint,9,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
}

func (x *MysteryShopNPC) Reset() {
	*x = MysteryShopNPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysteryShopNPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysteryShopNPC) ProtoMessage() {}

func (x *MysteryShopNPC) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysteryShopNPC.ProtoReflect.Descriptor instead.
func (*MysteryShopNPC) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{1}
}

func (x *MysteryShopNPC) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *MysteryShopNPC) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MysteryShopNPC) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *MysteryShopNPC) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *MysteryShopNPC) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *MysteryShopNPC) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MysteryShopNPC) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *MysteryShopNPC) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

func (x *MysteryShopNPC) GetOriginalPrice() int64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

type GetActiveNPCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active    bool            `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Npc       *MysteryShopNPC `protobuf:"bytes,2,opt,name=npc,proto3" json:"npc,omitempty"`
	StartTime int64           `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64           `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *GetActiveNPCReply) Reset() {
	*x = GetActiveNPCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveNPCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveNPCReply) ProtoMessage() {}

func (x *GetActiveNPCReply) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveNPCReply.ProtoReflect.Descriptor instead.
func (*GetActiveNPCReply) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{2}
}

func (x *GetActiveNPCReply) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetActiveNPCReply) GetNpc() *MysteryShopNPC {
	if x != nil {
		return x.Npc
	}
	return nil
}

func (x *GetActiveNPCReply) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetActiveNPCReply) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type BuyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NpcId int64 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{3}
}

func (x *BuyRequest) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

type MysteryShopReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId  int32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count   int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Field_6 int32 `protobuf:"varint,6,opt,name=field_6,json=field6,proto3" json:"field_6,omitempty"`
	Field_9 int32 `protobuf:"varint,9,opt,name=field_9,json=field9,proto3" json:"field_9,omitempty"`
}

func (x *MysteryShopReward) Reset() {
	*x = MysteryShopReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MysteryShopReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysteryShopReward) ProtoMessage() {}

func (x *MysteryShopReward) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysteryShopReward.ProtoReflect.Descriptor instead.
func (*MysteryShopReward) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{4}
}

func (x *MysteryShopReward) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MysteryShopReward) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MysteryShopReward) GetField_6() int32 {
	if x != nil {
		return x.Field_6
	}
	return 0
}

func (x *MysteryShopReward) GetField_9() int32 {
	if x != nil {
		return x.Field_9
	}
	return 0
}

type BuyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reward *MysteryShopReward `protobuf:"bytes,1,opt,name=reward,proto3" json:"reward,omitempty"`
	Npc    *MysteryShopNPC    `protobuf:"bytes,2,opt,name=npc,proto3" json:"npc,omitempty"`
}

func (x *BuyReply) Reset() {
	*x = BuyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyReply) ProtoMessage() {}

func (x *BuyReply) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyReply.ProtoReflect.Descriptor instead.
func (*BuyReply) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{5}
}

func (x *BuyReply) GetReward() *MysteryShopReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *BuyReply) GetNpc() *MysteryShopNPC {
	if x != nil {
		return x.Npc
	}
	return nil
}

type AbandonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbandonRequest) Reset() {
	*x = AbandonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonRequest) ProtoMessage() {}

func (x *AbandonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonRequest.ProtoReflect.Descriptor instead.
func (*AbandonRequest) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{6}
}

type AbandonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbandonReply) Reset() {
	*x = AbandonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mysteryshoppb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonReply) ProtoMessage() {}

func (x *AbandonReply) ProtoReflect() protoreflect.Message {
	mi := &file_mysteryshoppb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonReply.ProtoReflect.Descriptor instead.
func (*AbandonReply) Descriptor() ([]byte, []int) {
	return file_mysteryshoppb_proto_rawDescGZIP(), []int{7}
}

var File_mysteryshoppb_proto protoreflect.FileDescriptor

var file_mysteryshoppb_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79,
	0x73, 0x74, 0x65, 0x72, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x22, 0x15, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x94, 0x02, 0x0a, 0x0e, 0x4d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x53, 0x68,
	0x6f, 0x70, 0x4e, 0x50, 0x43, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x70, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x70, 0x63, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x36, 0x0a, 0x03, 0x6e, 0x70, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79,
	0x73, 0x74, 0x65, 0x72, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x73, 0x74,
	0x65, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x4e, 0x50, 0x43, 0x52, 0x03, 0x6e, 0x70, 0x63, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0a, 0x42, 0x75, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x70, 0x63, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x70, 0x63, 0x49, 0x64, 0x22, 0x74,
	0x0a, 0x11, 0x4d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x36, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x36, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x39, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x39, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3f, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65,
	0x72, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79,
	0x53, 0x68, 0x6f, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x36, 0x0a, 0x03, 0x6e, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79,
	0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x53, 0x68,
	0x6f, 0x70, 0x4e, 0x50, 0x43, 0x52, 0x03, 0x6e, 0x70, 0x63, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x62,
	0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c,
	0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x96, 0x02, 0x0a,
	0x12, 0x4d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x4e, 0x50, 0x43, 0x12, 0x29, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73,
	0x74, 0x65, 0x72, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x4e, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e,
	0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x03, 0x42, 0x75, 0x79, 0x12, 0x20,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72,
	0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x53, 0x0a, 0x07, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x62, 0x2e, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x6d, 0x79, 0x73, 0x74, 0x65,
	0x72, 0x79, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46,
	0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mysteryshoppb_proto_rawDescOnce sync.Once
	file_mysteryshoppb_proto_rawDescData = file_mysteryshoppb_proto_rawDesc
)

func file_mysteryshoppb_proto_rawDescGZIP() []byte {
	file_mysteryshoppb_proto_rawDescOnce.Do(func() {
		file_mysteryshoppb_proto_rawDescData = protoimpl.X.CompressGZIP(file_mysteryshoppb_proto_rawDescData)
	})
	return file_mysteryshoppb_proto_rawDescData
}

var file_mysteryshoppb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mysteryshoppb_proto_goTypes = []interface{}{
	(*GetActiveNPCRequest)(nil), // 0: gamepb.mysteryshoppb.GetActiveNPCRequest
	(*MysteryShopNPC)(nil),      // 1: gamepb.mysteryshoppb.MysteryShopNPC
	(*GetActiveNPCReply)(nil),   // 2: gamepb.mysteryshoppb.GetActiveNPCReply
	(*BuyRequest)(nil),          // 3: gamepb.mysteryshoppb.BuyRequest
	(*MysteryShopReward)(nil),   // 4: gamepb.mysteryshoppb.MysteryShopReward
	(*BuyReply)(nil),            // 5: gamepb.mysteryshoppb.BuyReply
	(*AbandonRequest)(nil),      // 6: gamepb.mysteryshoppb.AbandonRequest
	(*AbandonReply)(nil),        // 7: gamepb.mysteryshoppb.AbandonReply
}
var file_mysteryshoppb_proto_depIdxs = []int32{
	1, // 0: gamepb.mysteryshoppb.GetActiveNPCReply.npc:type_name -> gamepb.mysteryshoppb.MysteryShopNPC
	4, // 1: gamepb.mysteryshoppb.BuyReply.reward:type_name -> gamepb.mysteryshoppb.MysteryShopReward
	1, // 2: gamepb.mysteryshoppb.BuyReply.npc:type_name -> gamepb.mysteryshoppb.MysteryShopNPC
	0, // 3: gamepb.mysteryshoppb.MysteryShopService.GetActiveNPC:input_type -> gamepb.mysteryshoppb.GetActiveNPCRequest
	3, // 4: gamepb.mysteryshoppb.MysteryShopService.Buy:input_type -> gamepb.mysteryshoppb.BuyRequest
	6, // 5: gamepb.mysteryshoppb.MysteryShopService.Abandon:input_type -> gamepb.mysteryshoppb.AbandonRequest
	2, // 6: gamepb.mysteryshoppb.MysteryShopService.GetActiveNPC:output_type -> gamepb.mysteryshoppb.GetActiveNPCReply
	5, // 7: gamepb.mysteryshoppb.MysteryShopService.Buy:output_type -> gamepb.mysteryshoppb.BuyReply
	7, // 8: gamepb.mysteryshoppb.MysteryShopService.Abandon:output_type -> gamepb.mysteryshoppb.AbandonReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mysteryshoppb_proto_init() }
func file_mysteryshoppb_proto_init() {
	if File_mysteryshoppb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mysteryshoppb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveNPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysteryShopNPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveNPCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MysteryShopReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbandonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mysteryshoppb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbandonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mysteryshoppb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mysteryshoppb_proto_goTypes,
		DependencyIndexes: file_mysteryshoppb_proto_depIdxs,
		MessageInfos:      file_mysteryshoppb_proto_msgTypes,
	}.Build()
	File_mysteryshoppb_proto = out.File
	file_mysteryshoppb_proto_rawDesc = nil
	file_mysteryshoppb_proto_goTypes = nil
	file_mysteryshoppb_proto_depIdxs = nil
}
