// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: qqvippb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 获取QQ会员礼包状态 ---
type GetQQVipRewardsStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQQVipRewardsStatusRequest) Reset() {
	*x = GetQQVipRewardsStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qqvippb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQQVipRewardsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQQVipRewardsStatusRequest) ProtoMessage() {}

func (x *GetQQVipRewardsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qqvippb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQQVipRewardsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQQVipRewardsStatusRequest) Descriptor() ([]byte, []int) {
	return file_qqvippb_proto_rawDescGZIP(), []int{0}
}

type GetQQVipRewardsStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasGift  bool `protobuf:"varint,1,opt,name=has_gift,json=hasGift,proto3" json:"has_gift,omitempty"`    // 是否有礼包
	CanClaim bool `protobuf:"varint,2,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"` // 是否可以领取
}

func (x *GetQQVipRewardsStatusReply) Reset() {
	*x = GetQQVipRewardsStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qqvippb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQQVipRewardsStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQQVipRewardsStatusReply) ProtoMessage() {}

func (x *GetQQVipRewardsStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_qqvippb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQQVipRewardsStatusReply.ProtoReflect.Descriptor instead.
func (*GetQQVipRewardsStatusReply) Descriptor() ([]byte, []int) {
	return file_qqvippb_proto_rawDescGZIP(), []int{1}
}

func (x *GetQQVipRewardsStatusReply) GetHasGift() bool {
	if x != nil {
		return x.HasGift
	}
	return false
}

func (x *GetQQVipRewardsStatusReply) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

// --- 领取QQ会员礼包 ---
type ClaimQQVipRewardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VipTypes []int32 `protobuf:"varint,1,rep,packed,name=vip_types,json=vipTypes,proto3" json:"vip_types,omitempty"` // 1: QQ会员，2: 超级会员
}

func (x *ClaimQQVipRewardsRequest) Reset() {
	*x = ClaimQQVipRewardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qqvippb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimQQVipRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimQQVipRewardsRequest) ProtoMessage() {}

func (x *ClaimQQVipRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qqvippb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimQQVipRewardsRequest.ProtoReflect.Descriptor instead.
func (*ClaimQQVipRewardsRequest) Descriptor() ([]byte, []int) {
	return file_qqvippb_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimQQVipRewardsRequest) GetVipTypes() []int32 {
	if x != nil {
		return x.VipTypes
	}
	return nil
}

type ClaimQQVipRewardsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 奖励物品列表
}

func (x *ClaimQQVipRewardsReply) Reset() {
	*x = ClaimQQVipRewardsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qqvippb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimQQVipRewardsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimQQVipRewardsReply) ProtoMessage() {}

func (x *ClaimQQVipRewardsReply) ProtoReflect() protoreflect.Message {
	mi := &file_qqvippb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimQQVipRewardsReply.ProtoReflect.Descriptor instead.
func (*ClaimQQVipRewardsReply) Descriptor() ([]byte, []int) {
	return file_qqvippb_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimQQVipRewardsReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_qqvippb_proto protoreflect.FileDescriptor

var file_qqvippb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x71, 0x71, 0x76, 0x69, 0x70, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x71, 0x71, 0x76, 0x69, 0x70, 0x70, 0x62, 0x1a,
	0x0c, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x51, 0x51, 0x56, 0x69, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x51, 0x51, 0x56, 0x69, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x68,
	0x61, 0x73, 0x5f, 0x67, 0x69, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x47, 0x69, 0x66, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x6c,
	0x61, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x22, 0x37, 0x0a, 0x18, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x51, 0x51, 0x56, 0x69,
	0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x76, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x08, 0x76, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x16,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x51, 0x51, 0x56, 0x69, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c,
	0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qqvippb_proto_rawDescOnce sync.Once
	file_qqvippb_proto_rawDescData = file_qqvippb_proto_rawDesc
)

func file_qqvippb_proto_rawDescGZIP() []byte {
	file_qqvippb_proto_rawDescOnce.Do(func() {
		file_qqvippb_proto_rawDescData = protoimpl.X.CompressGZIP(file_qqvippb_proto_rawDescData)
	})
	return file_qqvippb_proto_rawDescData
}

var file_qqvippb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qqvippb_proto_goTypes = []interface{}{
	(*GetQQVipRewardsStatusRequest)(nil), // 0: gamepb.qqvippb.GetQQVipRewardsStatusRequest
	(*GetQQVipRewardsStatusReply)(nil),   // 1: gamepb.qqvippb.GetQQVipRewardsStatusReply
	(*ClaimQQVipRewardsRequest)(nil),     // 2: gamepb.qqvippb.ClaimQQVipRewardsRequest
	(*ClaimQQVipRewardsReply)(nil),       // 3: gamepb.qqvippb.ClaimQQVipRewardsReply
	(*Item)(nil),                         // 4: corepb.Item
}
var file_qqvippb_proto_depIdxs = []int32{
	4, // 0: gamepb.qqvippb.ClaimQQVipRewardsReply.items:type_name -> corepb.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_qqvippb_proto_init() }
func file_qqvippb_proto_init() {
	if File_qqvippb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_qqvippb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQQVipRewardsStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qqvippb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQQVipRewardsStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qqvippb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimQQVipRewardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qqvippb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimQQVipRewardsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qqvippb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qqvippb_proto_goTypes,
		DependencyIndexes: file_qqvippb_proto_depIdxs,
		MessageInfos:      file_qqvippb_proto_msgTypes,
	}.Build()
	File_qqvippb_proto = out.File
	file_qqvippb_proto_rawDesc = nil
	file_qqvippb_proto_goTypes = nil
	file_qqvippb_proto_depIdxs = nil
}
