// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: redpacketpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTodayClaimStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTodayClaimStatusRequest) Reset() {
	*x = GetTodayClaimStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redpacketpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodayClaimStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayClaimStatusRequest) ProtoMessage() {}

func (x *GetTodayClaimStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayClaimStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTodayClaimStatusRequest) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{0}
}

type RedPacketInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CanClaim bool  `protobuf:"varint,3,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
}

func (x *RedPacketInfo) Reset() {
	*x = RedPacketInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redpacketpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedPacketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedPacketInfo) ProtoMessage() {}

func (x *RedPacketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedPacketInfo.ProtoReflect.Descriptor instead.
func (*RedPacketInfo) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{1}
}

func (x *RedPacketInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RedPacketInfo) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

type GetTodayClaimStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*RedPacketInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *GetTodayClaimStatusReply) Reset() {
	*x = GetTodayClaimStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redpacketpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodayClaimStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayClaimStatusReply) ProtoMessage() {}

func (x *GetTodayClaimStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayClaimStatusReply.ProtoReflect.Descriptor instead.
func (*GetTodayClaimStatusReply) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodayClaimStatusReply) GetInfos() []*RedPacketInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ClaimRedPacketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClaimRedPacketRequest) Reset() {
	*x = ClaimRedPacketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redpacketpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimRedPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRedPacketRequest) ProtoMessage() {}

func (x *ClaimRedPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRedPacketRequest.ProtoReflect.Descriptor instead.
func (*ClaimRedPacketRequest) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimRedPacketRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClaimRedPacketReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Item   *Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *ClaimRedPacketReply) Reset() {
	*x = ClaimRedPacketReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redpacketpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimRedPacketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRedPacketReply) ProtoMessage() {}

func (x *ClaimRedPacketReply) ProtoReflect() protoreflect.Message {
	mi := &file_redpacketpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRedPacketReply.ProtoReflect.Descriptor instead.
func (*ClaimRedPacketReply) Descriptor() ([]byte, []int) {
	return file_redpacketpb_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimRedPacketReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ClaimRedPacketReply) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_redpacketpb_proto protoreflect.FileDescriptor

var file_redpacketpb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x65, 0x64, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x64, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x61,
	0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x0d, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x22, 0x53, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x64, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52,
	0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x4f, 0x0a, 0x13, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x32, 0xed, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x61,
	0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x64, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x64, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x64, 0x0a, 0x0e, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x29, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x64, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x70,
	0x62, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62,
	0x2e, 0x72, 0x65, 0x64, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52,
	0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f,
	0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redpacketpb_proto_rawDescOnce sync.Once
	file_redpacketpb_proto_rawDescData = file_redpacketpb_proto_rawDesc
)

func file_redpacketpb_proto_rawDescGZIP() []byte {
	file_redpacketpb_proto_rawDescOnce.Do(func() {
		file_redpacketpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_redpacketpb_proto_rawDescData)
	})
	return file_redpacketpb_proto_rawDescData
}

var file_redpacketpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_redpacketpb_proto_goTypes = []interface{}{
	(*GetTodayClaimStatusRequest)(nil), // 0: gamepb.redpacketpb.GetTodayClaimStatusRequest
	(*RedPacketInfo)(nil),              // 1: gamepb.redpacketpb.RedPacketInfo
	(*GetTodayClaimStatusReply)(nil),   // 2: gamepb.redpacketpb.GetTodayClaimStatusReply
	(*ClaimRedPacketRequest)(nil),      // 3: gamepb.redpacketpb.ClaimRedPacketRequest
	(*ClaimRedPacketReply)(nil),        // 4: gamepb.redpacketpb.ClaimRedPacketReply
	(*Item)(nil),                       // 5: corepb.Item
}
var file_redpacketpb_proto_depIdxs = []int32{
	1, // 0: gamepb.redpacketpb.GetTodayClaimStatusReply.infos:type_name -> gamepb.redpacketpb.RedPacketInfo
	5, // 1: gamepb.redpacketpb.ClaimRedPacketReply.item:type_name -> corepb.Item
	0, // 2: gamepb.redpacketpb.RedPacketService.GetTodayClaimStatus:input_type -> gamepb.redpacketpb.GetTodayClaimStatusRequest
	3, // 3: gamepb.redpacketpb.RedPacketService.ClaimRedPacket:input_type -> gamepb.redpacketpb.ClaimRedPacketRequest
	2, // 4: gamepb.redpacketpb.RedPacketService.GetTodayClaimStatus:output_type -> gamepb.redpacketpb.GetTodayClaimStatusReply
	4, // 5: gamepb.redpacketpb.RedPacketService.ClaimRedPacket:output_type -> gamepb.redpacketpb.ClaimRedPacketReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_redpacketpb_proto_init() }
func file_redpacketpb_proto_init() {
	if File_redpacketpb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_redpacketpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodayClaimStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redpacketpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedPacketInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redpacketpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodayClaimStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redpacketpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimRedPacketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redpacketpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimRedPacketReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redpacketpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redpacketpb_proto_goTypes,
		DependencyIndexes: file_redpacketpb_proto_depIdxs,
		MessageInfos:      file_redpacketpb_proto_msgTypes,
	}.Build()
	File_redpacketpb_proto = out.File
	file_redpacketpb_proto_rawDesc = nil
	file_redpacketpb_proto_goTypes = nil
	file_redpacketpb_proto_depIdxs = nil
}
