// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: sharepb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 检查是否可以分享 ---
type CheckCanShareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckCanShareRequest) Reset() {
	*x = CheckCanShareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharepb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCanShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCanShareRequest) ProtoMessage() {}

func (x *CheckCanShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCanShareRequest.ProtoReflect.Descriptor instead.
func (*CheckCanShareRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{0}
}

type CheckCanShareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanShare bool `protobuf:"varint,1,opt,name=can_share,json=canShare,proto3" json:"can_share,omitempty"` // 是否可以分享
}

func (x *CheckCanShareReply) Reset() {
	*x = CheckCanShareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharepb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCanShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCanShareReply) ProtoMessage() {}

func (x *CheckCanShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCanShareReply.ProtoReflect.Descriptor instead.
func (*CheckCanShareReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCanShareReply) GetCanShare() bool {
	if x != nil {
		return x.CanShare
	}
	return false
}

// --- 报告分享 ---
type ReportShareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shared bool `protobuf:"varint,1,opt,name=shared,proto3" json:"shared,omitempty"` // 是否已分享
}

func (x *ReportShareRequest) Reset() {
	*x = ReportShareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharepb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportShareRequest) ProtoMessage() {}

func (x *ReportShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportShareRequest.ProtoReflect.Descriptor instead.
func (*ReportShareRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{2}
}

func (x *ReportShareRequest) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

type ReportShareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
}

func (x *ReportShareReply) Reset() {
	*x = ReportShareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharepb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportShareReply) ProtoMessage() {}

func (x *ReportShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportShareReply.ProtoReflect.Descriptor instead.
func (*ReportShareReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{3}
}

func (x *ReportShareReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- 领取分享奖励 ---
type ClaimShareRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claimed bool `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"` // 请求领取
}

func (x *ClaimShareRewardRequest) Reset() {
	*x = ClaimShareRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharepb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimShareRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimShareRewardRequest) ProtoMessage() {}

func (x *ClaimShareRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimShareRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimShareRewardRequest) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimShareRewardRequest) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type ClaimShareRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // 是否成功
	HasReward bool    `protobuf:"varint,2,opt,name=has_reward,json=hasReward,proto3" json:"has_reward,omitempty"` // 是否有奖励
	Items     []*Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`                           // 奖励物品列表
}

func (x *ClaimShareRewardReply) Reset() {
	*x = ClaimShareRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sharepb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimShareRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimShareRewardReply) ProtoMessage() {}

func (x *ClaimShareRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_sharepb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimShareRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimShareRewardReply) Descriptor() ([]byte, []int) {
	return file_sharepb_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimShareRewardReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimShareRewardReply) GetHasReward() bool {
	if x != nil {
		return x.HasReward
	}
	return false
}

func (x *ClaimShareRewardReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_sharepb_proto protoreflect.FileDescriptor

var file_sharepb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x70, 0x62, 0x1a,
	0x0c, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a,
	0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x61,
	0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x61, 0x6e, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x63, 0x61, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x17, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x22, 0x74, 0x0a, 0x15, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x68, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x68, 0x61, 0x73, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42,
	0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f,
	0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sharepb_proto_rawDescOnce sync.Once
	file_sharepb_proto_rawDescData = file_sharepb_proto_rawDesc
)

func file_sharepb_proto_rawDescGZIP() []byte {
	file_sharepb_proto_rawDescOnce.Do(func() {
		file_sharepb_proto_rawDescData = protoimpl.X.CompressGZIP(file_sharepb_proto_rawDescData)
	})
	return file_sharepb_proto_rawDescData
}

var file_sharepb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sharepb_proto_goTypes = []interface{}{
	(*CheckCanShareRequest)(nil),    // 0: gamepb.sharepb.CheckCanShareRequest
	(*CheckCanShareReply)(nil),      // 1: gamepb.sharepb.CheckCanShareReply
	(*ReportShareRequest)(nil),      // 2: gamepb.sharepb.ReportShareRequest
	(*ReportShareReply)(nil),        // 3: gamepb.sharepb.ReportShareReply
	(*ClaimShareRewardRequest)(nil), // 4: gamepb.sharepb.ClaimShareRewardRequest
	(*ClaimShareRewardReply)(nil),   // 5: gamepb.sharepb.ClaimShareRewardReply
	(*Item)(nil),                    // 6: corepb.Item
}
var file_sharepb_proto_depIdxs = []int32{
	6, // 0: gamepb.sharepb.ClaimShareRewardReply.items:type_name -> corepb.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sharepb_proto_init() }
func file_sharepb_proto_init() {
	if File_sharepb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sharepb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCanShareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharepb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCanShareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharepb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportShareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharepb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportShareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharepb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimShareRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sharepb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimShareRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sharepb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sharepb_proto_goTypes,
		DependencyIndexes: file_sharepb_proto_depIdxs,
		MessageInfos:      file_sharepb_proto_msgTypes,
	}.Build()
	File_sharepb_proto = out.File
	file_sharepb_proto_rawDesc = nil
	file_sharepb_proto_goTypes = nil
	file_sharepb_proto_depIdxs = nil
}
