// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: shoppb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 解锁条件 ============
type CondType int32

const (
	CondType_COND_TYPE_UNKNOWN CondType = 0
	CondType_MIN_LEVEL         CondType = 1 // 最低等级要求
	CondType_UNLOCK_CARD       CondType = 2 // 需要解锁卡
)

// Enum value maps for CondType.
var (
	CondType_name = map[int32]string{
		0: "COND_TYPE_UNKNOWN",
		1: "MIN_LEVEL",
		2: "UNLOCK_CARD",
	}
	CondType_value = map[string]int32{
		"COND_TYPE_UNKNOWN": 0,
		"MIN_LEVEL":         1,
		"UNLOCK_CARD":       2,
	}
)

func (x CondType) Enum() *CondType {
	p := new(CondType)
	*p = x
	return p
}

func (x CondType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CondType) Descriptor() protoreflect.EnumDescriptor {
	return file_shoppb_proto_enumTypes[0].Descriptor()
}

func (CondType) Type() protoreflect.EnumType {
	return &file_shoppb_proto_enumTypes[0]
}

func (x CondType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CondType.Descriptor instead.
func (CondType) EnumDescriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{0}
}

// ============ 商店概览 ============
type ShopProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId   int64  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`       // 商店ID
	ShopName string `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`  // 商店名称
	ShopType int32  `protobuf:"varint,3,opt,name=shop_type,json=shopType,proto3" json:"shop_type,omitempty"` // 商店类型
}

func (x *ShopProfile) Reset() {
	*x = ShopProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfile) ProtoMessage() {}

func (x *ShopProfile) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfile.ProtoReflect.Descriptor instead.
func (*ShopProfile) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{0}
}

func (x *ShopProfile) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopProfile) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopProfile) GetShopType() int32 {
	if x != nil {
		return x.ShopType
	}
	return 0
}

// ============ 商品信息 ============
type GoodsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 商品ID (用于购买)
	BoughtNum  int64   `protobuf:"varint,2,opt,name=bought_num,json=boughtNum,proto3" json:"bought_num,omitempty"`    // 已购买数量
	Price      int64   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                             // 价格 (金币)
	LimitCount int64   `protobuf:"varint,4,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"` // 限购数量 (0=不限购)
	Unlocked   bool    `protobuf:"varint,5,opt,name=unlocked,proto3" json:"unlocked,omitempty"`                       // 是否已解锁
	ItemId     int64   `protobuf:"varint,6,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 物品ID (即种子ID)
	ItemCount  int64   `protobuf:"varint,7,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`    // 每次购买获得数量
	Conds      []*Cond `protobuf:"bytes,8,rep,name=conds,proto3" json:"conds,omitempty"`                              // 解锁条件
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetBoughtNum() int64 {
	if x != nil {
		return x.BoughtNum
	}
	return 0
}

func (x *GoodsInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfo) GetLimitCount() int64 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *GoodsInfo) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *GoodsInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GoodsInfo) GetItemCount() int64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *GoodsInfo) GetConds() []*Cond {
	if x != nil {
		return x.Conds
	}
	return nil
}

type Cond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`   // CondType
	Param int64 `protobuf:"varint,2,opt,name=param,proto3" json:"param,omitempty"` // 参数值 (如等级要求的等级数)
}

func (x *Cond) Reset() {
	*x = Cond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cond) ProtoMessage() {}

func (x *Cond) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cond.ProtoReflect.Descriptor instead.
func (*Cond) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{2}
}

func (x *Cond) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Cond) GetParam() int64 {
	if x != nil {
		return x.Param
	}
	return 0
}

// --- 获取商店列表 ---
type ShopProfilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShopProfilesRequest) Reset() {
	*x = ShopProfilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfilesRequest) ProtoMessage() {}

func (x *ShopProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfilesRequest.ProtoReflect.Descriptor instead.
func (*ShopProfilesRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{3}
}

type ShopProfilesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopProfiles []*ShopProfile `protobuf:"bytes,1,rep,name=shop_profiles,json=shopProfiles,proto3" json:"shop_profiles,omitempty"`
}

func (x *ShopProfilesReply) Reset() {
	*x = ShopProfilesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopProfilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopProfilesReply) ProtoMessage() {}

func (x *ShopProfilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopProfilesReply.ProtoReflect.Descriptor instead.
func (*ShopProfilesReply) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{4}
}

func (x *ShopProfilesReply) GetShopProfiles() []*ShopProfile {
	if x != nil {
		return x.ShopProfiles
	}
	return nil
}

// --- 获取商店商品 ---
type ShopInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int64 `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
}

func (x *ShopInfoRequest) Reset() {
	*x = ShopInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfoRequest) ProtoMessage() {}

func (x *ShopInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfoRequest.ProtoReflect.Descriptor instead.
func (*ShopInfoRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{5}
}

func (x *ShopInfoRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ShopInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsList []*GoodsInfo `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
}

func (x *ShopInfoReply) Reset() {
	*x = ShopInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfoReply) ProtoMessage() {}

func (x *ShopInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfoReply.ProtoReflect.Descriptor instead.
func (*ShopInfoReply) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{6}
}

func (x *ShopInfoReply) GetGoodsList() []*GoodsInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

// --- 购买商品 ---
type BuyGoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID (GoodsInfo.id)
	Num     int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                        // 购买数量
	Price   int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                    // 单价
}

func (x *BuyGoodsRequest) Reset() {
	*x = BuyGoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsRequest) ProtoMessage() {}

func (x *BuyGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsRequest.ProtoReflect.Descriptor instead.
func (*BuyGoodsRequest) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{7}
}

func (x *BuyGoodsRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *BuyGoodsRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BuyGoodsRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyGoodsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods     *GoodsInfo `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`                          // 更新后的商品信息
	GetItems  []*Item    `protobuf:"bytes,2,rep,name=get_items,json=getItems,proto3" json:"get_items,omitempty"`    // 获得的物品
	CostItems []*Item    `protobuf:"bytes,3,rep,name=cost_items,json=costItems,proto3" json:"cost_items,omitempty"` // 消耗的物品
}

func (x *BuyGoodsReply) Reset() {
	*x = BuyGoodsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyGoodsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGoodsReply) ProtoMessage() {}

func (x *BuyGoodsReply) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGoodsReply.ProtoReflect.Descriptor instead.
func (*BuyGoodsReply) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{8}
}

func (x *BuyGoodsReply) GetGoods() *GoodsInfo {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *BuyGoodsReply) GetGetItems() []*Item {
	if x != nil {
		return x.GetItems
	}
	return nil
}

func (x *BuyGoodsReply) GetCostItems() []*Item {
	if x != nil {
		return x.CostItems
	}
	return nil
}

// --- 商品解锁推送 ---
type GoodsUnlockNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsList []*GoodsInfo `protobuf:"bytes,1,rep,name=goods_list,json=goodsList,proto3" json:"goods_list,omitempty"`
}

func (x *GoodsUnlockNotify) Reset() {
	*x = GoodsUnlockNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsUnlockNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsUnlockNotify) ProtoMessage() {}

func (x *GoodsUnlockNotify) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsUnlockNotify.ProtoReflect.Descriptor instead.
func (*GoodsUnlockNotify) Descriptor() ([]byte, []int) {
	return file_shoppb_proto_rawDescGZIP(), []int{9}
}

func (x *GoodsUnlockNotify) GetGoodsList() []*GoodsInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

var File_shoppb_proto protoreflect.FileDescriptor

var file_shoppb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x1a, 0x0c, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0b, 0x53,
	0x68, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0xf0, 0x01,
	0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x6f, 0x75, 0x67, 0x68, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x62, 0x6f, 0x75, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x22, 0x30, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x11, 0x53, 0x68, 0x6f,
	0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f,
	0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22,
	0x2a, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0d, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x0a,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x0f, 0x42, 0x75, 0x79, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x0d,
	0x42, 0x75, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a,
	0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x29, 0x0a,
	0x09, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08,
	0x67, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x63, 0x6f, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4c, 0x0a, 0x11, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x37, 0x0a, 0x0a, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x62, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x2a, 0x41, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x49, 0x4e, 0x5f, 0x4c, 0x45,
	0x56, 0x45, 0x4c, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x5f,
	0x43, 0x41, 0x52, 0x44, 0x10, 0x02, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61, 0x2f,
	0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_shoppb_proto_rawDescOnce sync.Once
	file_shoppb_proto_rawDescData = file_shoppb_proto_rawDesc
)

func file_shoppb_proto_rawDescGZIP() []byte {
	file_shoppb_proto_rawDescOnce.Do(func() {
		file_shoppb_proto_rawDescData = protoimpl.X.CompressGZIP(file_shoppb_proto_rawDescData)
	})
	return file_shoppb_proto_rawDescData
}

var file_shoppb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shoppb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shoppb_proto_goTypes = []interface{}{
	(CondType)(0),               // 0: gamepb.shoppb.CondType
	(*ShopProfile)(nil),         // 1: gamepb.shoppb.ShopProfile
	(*GoodsInfo)(nil),           // 2: gamepb.shoppb.GoodsInfo
	(*Cond)(nil),                // 3: gamepb.shoppb.Cond
	(*ShopProfilesRequest)(nil), // 4: gamepb.shoppb.ShopProfilesRequest
	(*ShopProfilesReply)(nil),   // 5: gamepb.shoppb.ShopProfilesReply
	(*ShopInfoRequest)(nil),     // 6: gamepb.shoppb.ShopInfoRequest
	(*ShopInfoReply)(nil),       // 7: gamepb.shoppb.ShopInfoReply
	(*BuyGoodsRequest)(nil),     // 8: gamepb.shoppb.BuyGoodsRequest
	(*BuyGoodsReply)(nil),       // 9: gamepb.shoppb.BuyGoodsReply
	(*GoodsUnlockNotify)(nil),   // 10: gamepb.shoppb.GoodsUnlockNotify
	(*Item)(nil),                // 11: corepb.Item
}
var file_shoppb_proto_depIdxs = []int32{
	3,  // 0: gamepb.shoppb.GoodsInfo.conds:type_name -> gamepb.shoppb.Cond
	1,  // 1: gamepb.shoppb.ShopProfilesReply.shop_profiles:type_name -> gamepb.shoppb.ShopProfile
	2,  // 2: gamepb.shoppb.ShopInfoReply.goods_list:type_name -> gamepb.shoppb.GoodsInfo
	2,  // 3: gamepb.shoppb.BuyGoodsReply.goods:type_name -> gamepb.shoppb.GoodsInfo
	11, // 4: gamepb.shoppb.BuyGoodsReply.get_items:type_name -> corepb.Item
	11, // 5: gamepb.shoppb.BuyGoodsReply.cost_items:type_name -> corepb.Item
	2,  // 6: gamepb.shoppb.GoodsUnlockNotify.goods_list:type_name -> gamepb.shoppb.GoodsInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shoppb_proto_init() }
func file_shoppb_proto_init() {
	if File_shoppb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shoppb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopProfilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopProfilesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyGoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyGoodsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsUnlockNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shoppb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shoppb_proto_goTypes,
		DependencyIndexes: file_shoppb_proto_depIdxs,
		EnumInfos:         file_shoppb_proto_enumTypes,
		MessageInfos:      file_shoppb_proto_msgTypes,
	}.Build()
	File_shoppb_proto = out.File
	file_shoppb_proto_rawDesc = nil
	file_shoppb_proto_goTypes = nil
	file_shoppb_proto_depIdxs = nil
}
