// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: taskpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 活跃度奖励 ============
// ============ 活跃度类型 ============
type ActiveType int32

const (
	ActiveType_ACTIVE_TYPE_UNKNOWN ActiveType = 0
	ActiveType_DAILYACTIVE         ActiveType = 1 // 日活跃
	ActiveType_WEEKLYACTIVE        ActiveType = 2 // 周活跃
)

// Enum value maps for ActiveType.
var (
	ActiveType_name = map[int32]string{
		0: "ACTIVE_TYPE_UNKNOWN",
		1: "DAILYACTIVE",
		2: "WEEKLYACTIVE",
	}
	ActiveType_value = map[string]int32{
		"ACTIVE_TYPE_UNKNOWN": 0,
		"DAILYACTIVE":         1,
		"WEEKLYACTIVE":        2,
	}
)

func (x ActiveType) Enum() *ActiveType {
	p := new(ActiveType)
	*p = x
	return p
}

func (x ActiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_taskpb_proto_enumTypes[0].Descriptor()
}

func (ActiveType) Type() protoreflect.EnumType {
	return &file_taskpb_proto_enumTypes[0]
}

func (x ActiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActiveType.Descriptor instead.
func (ActiveType) EnumDescriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{0}
}

// ============ 活跃度状态 ============
type ActiveStatus int32

const (
	ActiveStatus_NONE_UNKNOWN ActiveStatus = 0
	ActiveStatus_WAIT         ActiveStatus = 1 // 未达标
	ActiveStatus_DONE         ActiveStatus = 2 // 已达标可领取
)

// Enum value maps for ActiveStatus.
var (
	ActiveStatus_name = map[int32]string{
		0: "NONE_UNKNOWN",
		1: "WAIT",
		2: "DONE",
	}
	ActiveStatus_value = map[string]int32{
		"NONE_UNKNOWN": 0,
		"WAIT":         1,
		"DONE":         2,
	}
)

func (x ActiveStatus) Enum() *ActiveStatus {
	p := new(ActiveStatus)
	*p = x
	return p
}

func (x ActiveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActiveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_taskpb_proto_enumTypes[1].Descriptor()
}

func (ActiveStatus) Type() protoreflect.EnumType {
	return &file_taskpb_proto_enumTypes[1]
}

func (x ActiveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActiveStatus.Descriptor instead.
func (ActiveStatus) EnumDescriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{1}
}

// ============ 单个任务 ============
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // 任务ID
	Progress      int64    `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`                                // 当前进度
	IsClaimed     bool     `protobuf:"varint,3,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"`             // 是否已领取
	IsUnlocked    bool     `protobuf:"varint,4,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`          // 是否已解锁
	Rewards       []*Item  `protobuf:"bytes,5,rep,name=rewards,proto3" json:"rewards,omitempty"`                                   // 奖励列表
	TotalProgress int64    `protobuf:"varint,6,opt,name=total_progress,json=totalProgress,proto3" json:"total_progress,omitempty"` // 总进度
	ShareMultiple int64    `protobuf:"varint,7,opt,name=share_multiple,json=shareMultiple,proto3" json:"share_multiple,omitempty"` // 分享倍数 (>1 表示可分享翻倍)
	Params        []string `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty"`                                     // 参数
	Desc          string   `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`                                         // 描述
	TaskType      int32    `protobuf:"varint,10,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`               // 任务类型
	Group         int64    `protobuf:"varint,11,opt,name=group,proto3" json:"group,omitempty"`                                     // 分组
	CondType      int64    `protobuf:"varint,12,opt,name=cond_type,json=condType,proto3" json:"cond_type,omitempty"`               // 条件类型
	IsShowText    int64    `protobuf:"varint,13,opt,name=is_show_text,json=isShowText,proto3" json:"is_show_text,omitempty"`       // 是否显示文本
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

func (x *Task) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

func (x *Task) GetRewards() []*Item {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *Task) GetTotalProgress() int64 {
	if x != nil {
		return x.TotalProgress
	}
	return 0
}

func (x *Task) GetShareMultiple() int64 {
	if x != nil {
		return x.ShareMultiple
	}
	return 0
}

func (x *Task) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Task) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetGroup() int64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Task) GetCondType() int64 {
	if x != nil {
		return x.CondType
	}
	return 0
}

func (x *Task) GetIsShowText() int64 {
	if x != nil {
		return x.IsShowText
	}
	return 0
}

// ============ 活跃度奖励项 ============
type ActiveReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointId      int64   `protobuf:"varint,1,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`                // 奖励档位ID
	NeedProgress int64   `protobuf:"varint,2,opt,name=need_progress,json=needProgress,proto3" json:"need_progress,omitempty"` // 所需进度
	Status       int32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                 // ActiveStatus
	Rewards      []*Item `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty"`                                // 奖励物品
}

func (x *ActiveReward) Reset() {
	*x = ActiveReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveReward) ProtoMessage() {}

func (x *ActiveReward) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveReward.ProtoReflect.Descriptor instead.
func (*ActiveReward) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveReward) GetPointId() int64 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *ActiveReward) GetNeedProgress() int64 {
	if x != nil {
		return x.NeedProgress
	}
	return 0
}

func (x *ActiveReward) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActiveReward) GetRewards() []*Item {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// ============ 活跃度 ============
type Active struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32           `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`         // ActiveType
	Progress int64           `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // 当前活跃度
	Rewards  []*ActiveReward `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`    // 各档位奖励
}

func (x *Active) Reset() {
	*x = Active{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Active) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Active) ProtoMessage() {}

func (x *Active) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Active.ProtoReflect.Descriptor instead.
func (*Active) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{2}
}

func (x *Active) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Active) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Active) GetRewards() []*ActiveReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// ============ 任务信息汇总 ============
type TaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrowthTasks []*Task   `protobuf:"bytes,1,rep,name=growth_tasks,json=growthTasks,proto3" json:"growth_tasks,omitempty"` // 成长任务列表
	DailyTasks  []*Task   `protobuf:"bytes,2,rep,name=daily_tasks,json=dailyTasks,proto3" json:"daily_tasks,omitempty"`    // 每日任务列表
	Tasks       []*Task   `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`                                // 其他任务
	Actives     []*Active `protobuf:"bytes,4,rep,name=actives,proto3" json:"actives,omitempty"`                            // 活跃度奖励
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{3}
}

func (x *TaskInfo) GetGrowthTasks() []*Task {
	if x != nil {
		return x.GrowthTasks
	}
	return nil
}

func (x *TaskInfo) GetDailyTasks() []*Task {
	if x != nil {
		return x.DailyTasks
	}
	return nil
}

func (x *TaskInfo) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskInfo) GetActives() []*Active {
	if x != nil {
		return x.Actives
	}
	return nil
}

// --- 获取任务信息 ---
type TaskInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskInfoRequest) Reset() {
	*x = TaskInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoRequest) ProtoMessage() {}

func (x *TaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoRequest.ProtoReflect.Descriptor instead.
func (*TaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{4}
}

type TaskInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *TaskInfo `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
}

func (x *TaskInfoReply) Reset() {
	*x = TaskInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoReply) ProtoMessage() {}

func (x *TaskInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoReply.ProtoReflect.Descriptor instead.
func (*TaskInfoReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{5}
}

func (x *TaskInfoReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

// --- 领取单个任务奖励 ---
type ClaimTaskRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // 任务ID
	DoShared bool  `protobuf:"varint,2,opt,name=do_shared,json=doShared,proto3" json:"do_shared,omitempty"` // 是否使用分享翻倍 (true=翻倍, false=普通领取)
}

func (x *ClaimTaskRewardRequest) Reset() {
	*x = ClaimTaskRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimTaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardRequest) ProtoMessage() {}

func (x *ClaimTaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimTaskRewardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClaimTaskRewardRequest) GetDoShared() bool {
	if x != nil {
		return x.DoShared
	}
	return false
}

type ClaimTaskRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items            []*Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`                                               // 获得的物品
	TaskInfo         *TaskInfo `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`                         // 更新后的任务信息
	CompensatedItems []*Item   `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"` // 补偿物品
}

func (x *ClaimTaskRewardReply) Reset() {
	*x = ClaimTaskRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimTaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardReply) ProtoMessage() {}

func (x *ClaimTaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimTaskRewardReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClaimTaskRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *ClaimTaskRewardReply) GetCompensatedItems() []*Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

// --- 批量领取任务奖励 ---
type BatchClaimTaskRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids      []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`                    // 任务ID列表
	DoShared bool    `protobuf:"varint,2,opt,name=do_shared,json=doShared,proto3" json:"do_shared,omitempty"` // 是否使用分享翻倍
}

func (x *BatchClaimTaskRewardRequest) Reset() {
	*x = BatchClaimTaskRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchClaimTaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimTaskRewardRequest) ProtoMessage() {}

func (x *BatchClaimTaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimTaskRewardRequest.ProtoReflect.Descriptor instead.
func (*BatchClaimTaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchClaimTaskRewardRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchClaimTaskRewardRequest) GetDoShared() bool {
	if x != nil {
		return x.DoShared
	}
	return false
}

type BatchClaimTaskRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items            []*Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TaskInfo         *TaskInfo `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	CompensatedItems []*Item   `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"`
}

func (x *BatchClaimTaskRewardReply) Reset() {
	*x = BatchClaimTaskRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchClaimTaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClaimTaskRewardReply) ProtoMessage() {}

func (x *BatchClaimTaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClaimTaskRewardReply.ProtoReflect.Descriptor instead.
func (*BatchClaimTaskRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{9}
}

func (x *BatchClaimTaskRewardReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchClaimTaskRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *BatchClaimTaskRewardReply) GetCompensatedItems() []*Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

// --- 领取活跃度奖励 ---
type ClaimDailyRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`                                // ActiveType
	PointIds []int64 `protobuf:"varint,2,rep,packed,name=point_ids,json=pointIds,proto3" json:"point_ids,omitempty"` // 要领取的奖励档位ID列表
}

func (x *ClaimDailyRewardRequest) Reset() {
	*x = ClaimDailyRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDailyRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDailyRewardRequest) ProtoMessage() {}

func (x *ClaimDailyRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDailyRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimDailyRewardRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimDailyRewardRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ClaimDailyRewardRequest) GetPointIds() []int64 {
	if x != nil {
		return x.PointIds
	}
	return nil
}

type ClaimDailyRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items            []*Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TaskInfo         *TaskInfo `protobuf:"bytes,2,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
	CompensatedItems []*Item   `protobuf:"bytes,3,rep,name=compensated_items,json=compensatedItems,proto3" json:"compensated_items,omitempty"`
}

func (x *ClaimDailyRewardReply) Reset() {
	*x = ClaimDailyRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDailyRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDailyRewardReply) ProtoMessage() {}

func (x *ClaimDailyRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDailyRewardReply.ProtoReflect.Descriptor instead.
func (*ClaimDailyRewardReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimDailyRewardReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClaimDailyRewardReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *ClaimDailyRewardReply) GetCompensatedItems() []*Item {
	if x != nil {
		return x.CompensatedItems
	}
	return nil
}

// --- 客户端上报进度 ---
type ClientReportProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress int64 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *ClientReportProgressRequest) Reset() {
	*x = ClientReportProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientReportProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReportProgressRequest) ProtoMessage() {}

func (x *ClientReportProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReportProgressRequest.ProtoReflect.Descriptor instead.
func (*ClientReportProgressRequest) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{12}
}

func (x *ClientReportProgressRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ClientReportProgressRequest) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type ClientReportProgressReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *TaskInfo `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
}

func (x *ClientReportProgressReply) Reset() {
	*x = ClientReportProgressReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientReportProgressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReportProgressReply) ProtoMessage() {}

func (x *ClientReportProgressReply) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReportProgressReply.ProtoReflect.Descriptor instead.
func (*ClientReportProgressReply) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{13}
}

func (x *ClientReportProgressReply) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

// 任务状态变化通知
type TaskInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *TaskInfo `protobuf:"bytes,1,opt,name=task_info,json=taskInfo,proto3" json:"task_info,omitempty"`
}

func (x *TaskInfoNotify) Reset() {
	*x = TaskInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_taskpb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoNotify) ProtoMessage() {}

func (x *TaskInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_taskpb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoNotify.ProtoReflect.Descriptor instead.
func (*TaskInfoNotify) Descriptor() ([]byte, []int) {
	return file_taskpb_proto_rawDescGZIP(), []int{14}
}

func (x *TaskInfoNotify) GetTaskInfo() *TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

var File_taskpb_proto protoreflect.FileDescriptor

var file_taskpb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x1a, 0x0c, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x03, 0x0a, 0x04,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x12, 0x26, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77,
	0x54, 0x65, 0x78, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x65, 0x65, 0x64, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a,
	0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0x6f, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x35, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x07, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x0b,
	0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x64,
	0x61, 0x69, 0x6c, 0x79, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2f, 0x0a, 0x07,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x22, 0x11, 0x0a,
	0x0f, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x45, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x45, 0x0a, 0x16, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0xab,
	0x01, 0x0a, 0x14, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x39, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70,
	0x65, 0x6e, 0x73, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4c, 0x0a, 0x1b,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x64, 0x6f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0xb0, 0x01, 0x0a, 0x19, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x34, 0x0a, 0x09,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x39, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x63, 0x6f, 0x6d,
	0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4a, 0x0a,
	0x17, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x15, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a,
	0x11, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x70,
	0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61,
	0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x52, 0x0a, 0x1b, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x51, 0x0a, 0x19,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x46, 0x0a, 0x0e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x48, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x44, 0x41, 0x49, 0x4c, 0x59, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x57, 0x45, 0x45, 0x4b, 0x4c, 0x59, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x02, 0x2a, 0x34, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x49, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c, 0x69, 0x66, 0x61,
	0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_taskpb_proto_rawDescOnce sync.Once
	file_taskpb_proto_rawDescData = file_taskpb_proto_rawDesc
)

func file_taskpb_proto_rawDescGZIP() []byte {
	file_taskpb_proto_rawDescOnce.Do(func() {
		file_taskpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_taskpb_proto_rawDescData)
	})
	return file_taskpb_proto_rawDescData
}

var file_taskpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_taskpb_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_taskpb_proto_goTypes = []interface{}{
	(ActiveType)(0),                     // 0: gamepb.taskpb.ActiveType
	(ActiveStatus)(0),                   // 1: gamepb.taskpb.ActiveStatus
	(*Task)(nil),                        // 2: gamepb.taskpb.Task
	(*ActiveReward)(nil),                // 3: gamepb.taskpb.ActiveReward
	(*Active)(nil),                      // 4: gamepb.taskpb.Active
	(*TaskInfo)(nil),                    // 5: gamepb.taskpb.TaskInfo
	(*TaskInfoRequest)(nil),             // 6: gamepb.taskpb.TaskInfoRequest
	(*TaskInfoReply)(nil),               // 7: gamepb.taskpb.TaskInfoReply
	(*ClaimTaskRewardRequest)(nil),      // 8: gamepb.taskpb.ClaimTaskRewardRequest
	(*ClaimTaskRewardReply)(nil),        // 9: gamepb.taskpb.ClaimTaskRewardReply
	(*BatchClaimTaskRewardRequest)(nil), // 10: gamepb.taskpb.BatchClaimTaskRewardRequest
	(*BatchClaimTaskRewardReply)(nil),   // 11: gamepb.taskpb.BatchClaimTaskRewardReply
	(*ClaimDailyRewardRequest)(nil),     // 12: gamepb.taskpb.ClaimDailyRewardRequest
	(*ClaimDailyRewardReply)(nil),       // 13: gamepb.taskpb.ClaimDailyRewardReply
	(*ClientReportProgressRequest)(nil), // 14: gamepb.taskpb.ClientReportProgressRequest
	(*ClientReportProgressReply)(nil),   // 15: gamepb.taskpb.ClientReportProgressReply
	(*TaskInfoNotify)(nil),              // 16: gamepb.taskpb.TaskInfoNotify
	(*Item)(nil),                        // 17: corepb.Item
}
var file_taskpb_proto_depIdxs = []int32{
	17, // 0: gamepb.taskpb.Task.rewards:type_name -> corepb.Item
	17, // 1: gamepb.taskpb.ActiveReward.rewards:type_name -> corepb.Item
	3,  // 2: gamepb.taskpb.Active.rewards:type_name -> gamepb.taskpb.ActiveReward
	2,  // 3: gamepb.taskpb.TaskInfo.growth_tasks:type_name -> gamepb.taskpb.Task
	2,  // 4: gamepb.taskpb.TaskInfo.daily_tasks:type_name -> gamepb.taskpb.Task
	2,  // 5: gamepb.taskpb.TaskInfo.tasks:type_name -> gamepb.taskpb.Task
	4,  // 6: gamepb.taskpb.TaskInfo.actives:type_name -> gamepb.taskpb.Active
	5,  // 7: gamepb.taskpb.TaskInfoReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	17, // 8: gamepb.taskpb.ClaimTaskRewardReply.items:type_name -> corepb.Item
	5,  // 9: gamepb.taskpb.ClaimTaskRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	17, // 10: gamepb.taskpb.ClaimTaskRewardReply.compensated_items:type_name -> corepb.Item
	17, // 11: gamepb.taskpb.BatchClaimTaskRewardReply.items:type_name -> corepb.Item
	5,  // 12: gamepb.taskpb.BatchClaimTaskRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	17, // 13: gamepb.taskpb.BatchClaimTaskRewardReply.compensated_items:type_name -> corepb.Item
	17, // 14: gamepb.taskpb.ClaimDailyRewardReply.items:type_name -> corepb.Item
	5,  // 15: gamepb.taskpb.ClaimDailyRewardReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	17, // 16: gamepb.taskpb.ClaimDailyRewardReply.compensated_items:type_name -> corepb.Item
	5,  // 17: gamepb.taskpb.ClientReportProgressReply.task_info:type_name -> gamepb.taskpb.TaskInfo
	5,  // 18: gamepb.taskpb.TaskInfoNotify.task_info:type_name -> gamepb.taskpb.TaskInfo
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_taskpb_proto_init() }
func file_taskpb_proto_init() {
	if File_taskpb_proto != nil {
		return
	}
	file_corepb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_taskpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Active); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimTaskRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimTaskRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchClaimTaskRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchClaimTaskRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDailyRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDailyRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientReportProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientReportProgressReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_taskpb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_taskpb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskpb_proto_goTypes,
		DependencyIndexes: file_taskpb_proto_depIdxs,
		EnumInfos:         file_taskpb_proto_enumTypes,
		MessageInfos:      file_taskpb_proto_msgTypes,
	}.Build()
	File_taskpb_proto = out.File
	file_taskpb_proto_rawDesc = nil
	file_taskpb_proto_goTypes = nil
	file_taskpb_proto_depIdxs = nil
}
