// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: visitpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 进入原因枚举 ============
type EnterReason int32

const (
	EnterReason_ENTER_REASON_UNKNOWN  EnterReason = 0
	EnterReason_ENTER_REASON_BUBBLE   EnterReason = 1
	EnterReason_ENTER_REASON_FRIEND   EnterReason = 2
	EnterReason_ENTER_REASON_INTERACT EnterReason = 3
)

// Enum value maps for EnterReason.
var (
	EnterReason_name = map[int32]string{
		0: "ENTER_REASON_UNKNOWN",
		1: "ENTER_REASON_BUBBLE",
		2: "ENTER_REASON_FRIEND",
		3: "ENTER_REASON_INTERACT",
	}
	EnterReason_value = map[string]int32{
		"ENTER_REASON_UNKNOWN":  0,
		"ENTER_REASON_BUBBLE":   1,
		"ENTER_REASON_FRIEND":   2,
		"ENTER_REASON_INTERACT": 3,
	}
)

func (x EnterReason) Enum() *EnterReason {
	p := new(EnterReason)
	*p = x
	return p
}

func (x EnterReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnterReason) Descriptor() protoreflect.EnumDescriptor {
	return file_visitpb_proto_enumTypes[0].Descriptor()
}

func (EnterReason) Type() protoreflect.EnumType {
	return &file_visitpb_proto_enumTypes[0]
}

func (x EnterReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnterReason.Descriptor instead.
func (EnterReason) EnumDescriptor() ([]byte, []int) {
	return file_visitpb_proto_rawDescGZIP(), []int{0}
}

type BriefDogInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DogId   int64  `protobuf:"varint,1,opt,name=dog_id,json=dogId,proto3" json:"dog_id,omitempty"`       // 护主犬ID (常见: 90001/90002/90003/90011/90021)
	Status  int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                  // 状态位（推测）
	LeftSec int64  `protobuf:"varint,3,opt,name=left_sec,json=leftSec,proto3" json:"left_sec,omitempty"` // 剩余秒数（推测）
	Extra   []byte `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`                    // 预留扩展
}

func (x *BriefDogInfo) Reset() {
	*x = BriefDogInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BriefDogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefDogInfo) ProtoMessage() {}

func (x *BriefDogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_visitpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefDogInfo.ProtoReflect.Descriptor instead.
func (*BriefDogInfo) Descriptor() ([]byte, []int) {
	return file_visitpb_proto_rawDescGZIP(), []int{0}
}

func (x *BriefDogInfo) GetDogId() int64 {
	if x != nil {
		return x.DogId
	}
	return 0
}

func (x *BriefDogInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BriefDogInfo) GetLeftSec() int64 {
	if x != nil {
		return x.LeftSec
	}
	return 0
}

func (x *BriefDogInfo) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

// ============ 进入好友农场 ============
type EnterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostGid int64 `protobuf:"varint,1,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"` // 好友的GID
	Reason  int32 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`                  // EnterReason 进入原因（偷菜=2；主动加好友=5）
	// field 3 = 0（客户端加好友时显式带 0，proto3 默认值可省略）
	VisitToken string `protobuf:"bytes,7,opt,name=visit_token,json=visitToken,proto3" json:"visit_token,omitempty"` // 加好友流程的会话 nonce（32位hex），ApplyFriend 用 sha256(visit_token:gid) 校验
}

func (x *EnterRequest) Reset() {
	*x = EnterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRequest) ProtoMessage() {}

func (x *EnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRequest.ProtoReflect.Descriptor instead.
func (*EnterRequest) Descriptor() ([]byte, []int) {
	return file_visitpb_proto_rawDescGZIP(), []int{1}
}

func (x *EnterRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

func (x *EnterRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *EnterRequest) GetVisitToken() string {
	if x != nil {
		return x.VisitToken
	}
	return ""
}

type EnterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basic        *BasicInfo  `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`                                     // 好友基本信息
	Lands        []*LandInfo `protobuf:"bytes,2,rep,name=lands,proto3" json:"lands,omitempty"`                                     // 好友的所有土地
	BriefDogInfo []byte      `protobuf:"bytes,3,opt,name=brief_dog_info,json=briefDogInfo,proto3" json:"brief_dog_info,omitempty"` // 好友当前农场护主犬摘要(抓包: length-delimited)
	NudgeInfo    []byte      `protobuf:"bytes,4,opt,name=nudge_info,json=nudgeInfo,proto3" json:"nudge_info,omitempty"`            // 催熟信息(抓包: length-delimited)
}

func (x *EnterReply) Reset() {
	*x = EnterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterReply) ProtoMessage() {}

func (x *EnterReply) ProtoReflect() protoreflect.Message {
	mi := &file_visitpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterReply.ProtoReflect.Descriptor instead.
func (*EnterReply) Descriptor() ([]byte, []int) {
	return file_visitpb_proto_rawDescGZIP(), []int{2}
}

func (x *EnterReply) GetBasic() *BasicInfo {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *EnterReply) GetLands() []*LandInfo {
	if x != nil {
		return x.Lands
	}
	return nil
}

func (x *EnterReply) GetBriefDogInfo() []byte {
	if x != nil {
		return x.BriefDogInfo
	}
	return nil
}

func (x *EnterReply) GetNudgeInfo() []byte {
	if x != nil {
		return x.NudgeInfo
	}
	return nil
}

// ============ 离开好友农场 ============
type LeaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostGid int64 `protobuf:"varint,1,opt,name=host_gid,json=hostGid,proto3" json:"host_gid,omitempty"` // 好友的GID
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visitpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_visitpb_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRequest) GetHostGid() int64 {
	if x != nil {
		return x.HostGid
	}
	return 0
}

type LeaveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveReply) Reset() {
	*x = LeaveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_visitpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveReply) ProtoMessage() {}

func (x *LeaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_visitpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveReply.ProtoReflect.Descriptor instead.
func (*LeaveReply) Descriptor() ([]byte, []int) {
	return file_visitpb_proto_rawDescGZIP(), []int{4}
}

var File_visitpb_proto protoreflect.FileDescriptor

var file_visitpb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x74, 0x70, 0x62, 0x1a,
	0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0c,
	0x42, 0x72, 0x69, 0x65, 0x66, 0x44, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06,
	0x64, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x6f,
	0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x65, 0x66, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c,
	0x65, 0x66, 0x74, 0x53, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x62, 0x0a, 0x0c,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x68, 0x6f, 0x73, 0x74, 0x47, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x76, 0x69, 0x73, 0x69, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0xb1, 0x01, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2e, 0x0a, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x12,
	0x2e, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x70, 0x62, 0x2e,
	0x4c, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x24, 0x0a, 0x0e, 0x62, 0x72, 0x69, 0x65, 0x66, 0x5f, 0x64, 0x6f, 0x67, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x62, 0x72, 0x69, 0x65, 0x66, 0x44, 0x6f,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x75, 0x64, 0x67, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6e, 0x75, 0x64, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x29, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x67, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x47, 0x69, 0x64, 0x22,
	0x0c, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x74, 0x0a,
	0x0b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x14,
	0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f,
	0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x42, 0x55, 0x42, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x17, 0x0a, 0x13, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f,
	0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x4e, 0x54, 0x45,
	0x52, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x41, 0x43,
	0x54, 0x10, 0x03, 0x32, 0x94, 0x01, 0x0a, 0x0c, 0x56, 0x69, 0x73, 0x69, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x70, 0x62, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x12, 0x1c, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x74, 0x70,
	0x62, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x74, 0x70, 0x62, 0x2e,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x73, 0x65, 0x4b, 0x68, 0x6c,
	0x69, 0x66, 0x61, 0x2f, 0x46, 0x61, 0x72, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_visitpb_proto_rawDescOnce sync.Once
	file_visitpb_proto_rawDescData = file_visitpb_proto_rawDesc
)

func file_visitpb_proto_rawDescGZIP() []byte {
	file_visitpb_proto_rawDescOnce.Do(func() {
		file_visitpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_visitpb_proto_rawDescData)
	})
	return file_visitpb_proto_rawDescData
}

var file_visitpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_visitpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_visitpb_proto_goTypes = []interface{}{
	(EnterReason)(0),     // 0: gamepb.visitpb.EnterReason
	(*BriefDogInfo)(nil), // 1: gamepb.visitpb.BriefDogInfo
	(*EnterRequest)(nil), // 2: gamepb.visitpb.EnterRequest
	(*EnterReply)(nil),   // 3: gamepb.visitpb.EnterReply
	(*LeaveRequest)(nil), // 4: gamepb.visitpb.LeaveRequest
	(*LeaveReply)(nil),   // 5: gamepb.visitpb.LeaveReply
	(*BasicInfo)(nil),    // 6: gamepb.userpb.BasicInfo
	(*LandInfo)(nil),     // 7: gamepb.plantpb.LandInfo
}
var file_visitpb_proto_depIdxs = []int32{
	6, // 0: gamepb.visitpb.EnterReply.basic:type_name -> gamepb.userpb.BasicInfo
	7, // 1: gamepb.visitpb.EnterReply.lands:type_name -> gamepb.plantpb.LandInfo
	2, // 2: gamepb.visitpb.VisitService.Enter:input_type -> gamepb.visitpb.EnterRequest
	4, // 3: gamepb.visitpb.VisitService.Leave:input_type -> gamepb.visitpb.LeaveRequest
	3, // 4: gamepb.visitpb.VisitService.Enter:output_type -> gamepb.visitpb.EnterReply
	5, // 5: gamepb.visitpb.VisitService.Leave:output_type -> gamepb.visitpb.LeaveReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_visitpb_proto_init() }
func file_visitpb_proto_init() {
	if File_visitpb_proto != nil {
		return
	}
	file_plantpb_proto_init()
	file_userpb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_visitpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BriefDogInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_visitpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_visitpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_visitpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_visitpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_visitpb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_visitpb_proto_goTypes,
		DependencyIndexes: file_visitpb_proto_depIdxs,
		EnumInfos:         file_visitpb_proto_enumTypes,
		MessageInfos:      file_visitpb_proto_msgTypes,
	}.Build()
	File_visitpb_proto = out.File
	file_visitpb_proto_rawDesc = nil
	file_visitpb_proto_goTypes = nil
	file_visitpb_proto_depIdxs = nil
}
