// Command protogen regenerates protobuf bindings when protoc is installed and
// validates the committed bindings otherwise.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const goPackage = "github.com/RoseKhlifa/FarmBot/internal/game/pb;pb"

func main() {
	root, err := repositoryRoot()
	if err != nil {
		fatal(err)
	}
	protoFiles, err := filepath.Glob(filepath.Join(root, "proto", "*.proto"))
	if err != nil {
		fatal(fmt.Errorf("list proto sources: %w", err))
	}
	sort.Strings(protoFiles)
	if len(protoFiles) != 22 {
		fatal(fmt.Errorf("found %d proto sources, want 22", len(protoFiles)))
	}

	if protoc, lookupErr := exec.LookPath("protoc"); lookupErr == nil {
		if err := generate(root, protoc, protoFiles); err != nil {
			fatal(err)
		}
		fmt.Println("generated 22 protobuf bindings")
		return
	}
	if err := verifyCommitted(root, protoFiles); err != nil {
		fatal(fmt.Errorf("protoc is unavailable and committed bindings are invalid: %w", err))
	}
	fmt.Println("protoc is unavailable; verified 22 committed protobuf bindings")
}

func repositoryRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("resolve working directory: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod was not found in this directory or its parents")
		}
		dir = parent
	}
}

func generate(root, protoc string, protoFiles []string) error {
	if _, err := exec.LookPath("protoc-gen-go"); err != nil {
		return errors.New("protoc-gen-go is required; run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest")
	}
	args := []string{
		"--proto_path=" + filepath.Join(root, "proto"),
		"--go_out=paths=source_relative:" + filepath.Join(root, "internal", "game", "pb"),
	}
	args = append(args, protoFiles...)
	command := exec.Command(protoc, args...)
	command.Dir = root
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Errorf("run protoc: %w", err)
	}
	return verifyCommitted(root, protoFiles)
}

func verifyCommitted(root string, protoFiles []string) error {
	generated, err := filepath.Glob(filepath.Join(root, "internal", "game", "pb", "*.pb.go"))
	if err != nil {
		return fmt.Errorf("list generated bindings: %w", err)
	}
	if len(generated) != len(protoFiles) {
		return fmt.Errorf("found %d generated bindings for %d proto sources", len(generated), len(protoFiles))
	}
	for _, source := range protoFiles {
		data, err := os.ReadFile(source)
		if err != nil {
			return fmt.Errorf("read %s: %w", filepath.Base(source), err)
		}
		option := []byte(`option go_package = "` + goPackage + `";`)
		if !bytes.Contains(data, option) {
			return fmt.Errorf("%s has an invalid go_package", filepath.Base(source))
		}
		name := strings.TrimSuffix(filepath.Base(source), filepath.Ext(source))
		binding := filepath.Join(root, "internal", "game", "pb", name+".pb.go")
		generatedData, err := os.ReadFile(binding)
		if err != nil {
			return fmt.Errorf("read binding for %s: %w", filepath.Base(source), err)
		}
		if !bytes.Contains(generatedData, []byte("Code generated by protoc-gen-go. DO NOT EDIT.")) ||
			!bytes.Contains(generatedData, []byte("// source: "+filepath.Base(source))) ||
			!bytes.Contains(generatedData, []byte("package pb")) {
			return fmt.Errorf("%s is not the expected generated Go binding", filepath.Base(binding))
		}
	}
	return nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-proto:", err)
	os.Exit(1)
}
